/**
 *  Copyright IBM Corporation 2018, 2019
 */


// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.12.05 at 04:58:13 PM PST 
//


package commands.update.tran;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlType;


/**
 * A UpUpdateTran object represents an OM Update
 * 						Transaction Command Interaction.
 * 					
 * 
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "UpdateTran", propOrder = {
    "name",
    "_class",
    "start",
    "stop",
    "startstop",
    "set",
    "option",
    "scope"
})
public class UpdateTran {

    @XmlElement(name = "NAME", required = true)
    protected List<String> name;
    @XmlElement(name = "CLASS", type = Integer.class)
    protected List<Integer> _class;
    @XmlElement(name = "START")
    protected List<UpdateTran.StartOptions> start;
    @XmlElement(name = "STOP")
    protected List<UpdateTran.StopOptions> stop;
    @XmlElement(name = "STARTSTOP")
    protected List<UpdateTran.STARTSTOP> startstop;
    @XmlElement(name = "SET")
    protected UpdateTran.SET set;
    @XmlElement(name = "OPTION")
    protected List<UpdateTran.OptionOptions> option;
    @XmlElement(name = "SCOPE")
    protected UpdateTran.ScopeOptions scope;

    /**
     * Gets the value of the name property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the name property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getNAME().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     * 
     * 
     */
    public List<String> getNAME() {
        if (name == null) {
            name = new ArrayList<String>();
        }
        return this.name;
    }

    /**
     * Gets the value of the class property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the class property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getCLASS().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Integer }
     * 
     * 
     */
    public List<Integer> getCLASS() {
        if (_class == null) {
            _class = new ArrayList<Integer>();
        }
        return this._class;
    }

    /**
     * Gets the value of the start property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the start property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getSTART().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link UpdateTran.StartOptions }
     * 
     * 
     */
    public List<UpdateTran.StartOptions> getSTART() {
        if (start == null) {
            start = new ArrayList<UpdateTran.StartOptions>();
        }
        return this.start;
    }

    /**
     * Gets the value of the stop property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the stop property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getSTOP().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link UpdateTran.StopOptions }
     * 
     * 
     */
    public List<UpdateTran.StopOptions> getSTOP() {
        if (stop == null) {
            stop = new ArrayList<UpdateTran.StopOptions>();
        }
        return this.stop;
    }

    /**
     * Gets the value of the startstop property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the startstop property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getSTARTSTOP().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link UpdateTran.STARTSTOP }
     * 
     * 
     */
    public List<UpdateTran.STARTSTOP> getSTARTSTOP() {
        if (startstop == null) {
            startstop = new ArrayList<UpdateTran.STARTSTOP>();
        }
        return this.startstop;
    }

    /**
     * Gets the value of the set property.
     * 
     * @return
     *     possible object is
     *     {@link UpdateTran.SET }
     *     
     */
    public UpdateTran.SET getSET() {
        return set;
    }

    /**
     * Sets the value of the set property.
     * 
     * @param value
     *     allowed object is
     *     {@link UpdateTran.SET }
     *     
     */
    public void setSET(UpdateTran.SET value) {
        this.set = value;
    }

    /**
     * Gets the value of the option property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the option property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getOPTION().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link UpdateTran.OptionOptions }
     * 
     * 
     */
    public List<UpdateTran.OptionOptions> getOPTION() {
        if (option == null) {
            option = new ArrayList<UpdateTran.OptionOptions>();
        }
        return this.option;
    }

    /**
     * Gets the value of the scope property.
     * 
     * @return
     *     possible object is
     *     {@link UpdateTran.ScopeOptions }
     *     
     */
    public UpdateTran.ScopeOptions getSCOPE() {
        return scope;
    }

    /**
     * Sets the value of the scope property.
     * 
     * @param value
     *     allowed object is
     *     {@link UpdateTran.ScopeOptions }
     *     
     */
    public void setSCOPE(UpdateTran.ScopeOptions value) {
        this.scope = value;
    }


    /**
     * <p>Java class for null.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * <p>
     * <pre>
     * &lt;simpleType>
     *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
     *     &lt;enumeration value="AFFIN"/>
     *     &lt;enumeration value="ALLRSP"/>
     *   &lt;/restriction>
     * &lt;/simpleType>
     * </pre>
     * 
     */
    @XmlType(name = "")
    @XmlEnum
    public enum OptionOptions {

        AFFIN,
        ALLRSP;

        public String value() {
            return name();
        }

        public static UpdateTran.OptionOptions fromValue(String v) {
            return valueOf(v);
        }

    }


    /**
     * <p>Java class for null.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * <p>
     * <pre>
     * &lt;simpleType>
     *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
     *     &lt;enumeration value="ALL"/>
     *     &lt;enumeration value="ACTIVE"/>
     *   &lt;/restriction>
     * &lt;/simpleType>
     * </pre>
     * 
     */
    @XmlType(name = "")
    @XmlEnum
    public enum ScopeOptions {

        ALL,
        ACTIVE;

        public String value() {
            return name();
        }

        public static UpdateTran.ScopeOptions fromValue(String v) {
            return valueOf(v);
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="AOCMD" minOccurs="0">
     *           &lt;simpleType>
     *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
     *               &lt;enumeration value="CMD"/>
     *               &lt;enumeration value="N"/>
     *               &lt;enumeration value="TRAN"/>
     *               &lt;enumeration value="Y"/>
     *             &lt;/restriction>
     *           &lt;/simpleType>
     *         &lt;/element>
     *         &lt;element name="CLASS" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
     *         &lt;element name="CMTMODE" minOccurs="0">
     *           &lt;simpleType>
     *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
     *               &lt;enumeration value="MULT"/>
     *               &lt;enumeration value="SNGL"/>
     *             &lt;/restriction>
     *           &lt;/simpleType>
     *         &lt;/element>
     *         &lt;element name="CONV" minOccurs="0">
     *           &lt;simpleType>
     *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
     *               &lt;enumeration value="N"/>
     *               &lt;enumeration value="Y"/>
     *             &lt;/restriction>
     *           &lt;/simpleType>
     *         &lt;/element>
     *         &lt;element name="CPRI" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
     *         &lt;element name="DCLWA" minOccurs="0">
     *           &lt;simpleType>
     *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
     *               &lt;enumeration value="N"/>
     *               &lt;enumeration value="Y"/>
     *             &lt;/restriction>
     *           &lt;/simpleType>
     *         &lt;/element>
     *         &lt;element name="DIRROUTE" minOccurs="0">
     *           &lt;simpleType>
     *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
     *               &lt;enumeration value="N"/>
     *               &lt;enumeration value="Y"/>
     *             &lt;/restriction>
     *           &lt;/simpleType>
     *         &lt;/element>
     *         &lt;element name="EDITRTN" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *         &lt;element name="EDITUC" minOccurs="0">
     *           &lt;simpleType>
     *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
     *               &lt;enumeration value="N"/>
     *               &lt;enumeration value="Y"/>
     *             &lt;/restriction>
     *           &lt;/simpleType>
     *         &lt;/element>
     *         &lt;element name="EMHBSZ" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
     *         &lt;element name="EXPRTIME" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
     *         &lt;element name="FP" minOccurs="0">
     *           &lt;simpleType>
     *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
     *               &lt;enumeration value="E"/>
     *               &lt;enumeration value="N"/>
     *               &lt;enumeration value="P"/>
     *             &lt;/restriction>
     *           &lt;/simpleType>
     *         &lt;/element>
     *         &lt;element name="INQ" minOccurs="0">
     *           &lt;simpleType>
     *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
     *               &lt;enumeration value="N"/>
     *               &lt;enumeration value="Y"/>
     *             &lt;/restriction>
     *           &lt;/simpleType>
     *         &lt;/element>
     *         &lt;element name="LCT" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
     *         &lt;element name="LOCK" minOccurs="0">
     *           &lt;simpleType>
     *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
     *               &lt;enumeration value="ON"/>
     *               &lt;enumeration value="OFF"/>
     *             &lt;/restriction>
     *           &lt;/simpleType>
     *         &lt;/element>
     *         &lt;element name="LPRI" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
     *         &lt;element name="MAXRGN" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
     *         &lt;element name="MSGTYPE" minOccurs="0">
     *           &lt;simpleType>
     *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
     *               &lt;enumeration value="MULTSEG"/>
     *               &lt;enumeration value="SNGLSEG"/>
     *             &lt;/restriction>
     *           &lt;/simpleType>
     *         &lt;/element>
     *         &lt;element name="MSNAME" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *         &lt;element name="NPRI" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
     *         &lt;element name="PARLIM" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
     *         &lt;element name="PGM" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *         &lt;element name="PLCT" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
     *         &lt;element name="PLCTTIME" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
     *         &lt;element name="RECOVER" minOccurs="0">
     *           &lt;simpleType>
     *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
     *               &lt;enumeration value="N"/>
     *               &lt;enumeration value="Y"/>
     *             &lt;/restriction>
     *           &lt;/simpleType>
     *         &lt;/element>
     *         &lt;element name="REMOTE" minOccurs="0">
     *           &lt;simpleType>
     *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
     *               &lt;enumeration value="N"/>
     *               &lt;enumeration value="Y"/>
     *             &lt;/restriction>
     *           &lt;/simpleType>
     *         &lt;/element>
     *         &lt;element name="RESP" minOccurs="0">
     *           &lt;simpleType>
     *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
     *               &lt;enumeration value="N"/>
     *               &lt;enumeration value="Y"/>
     *             &lt;/restriction>
     *           &lt;/simpleType>
     *         &lt;/element>
     *         &lt;element name="SEGNO" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
     *         &lt;element name="SEGSZ" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
     *         &lt;element name="SERIAL" minOccurs="0">
     *           &lt;simpleType>
     *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
     *               &lt;enumeration value="N"/>
     *               &lt;enumeration value="Y"/>
     *             &lt;/restriction>
     *           &lt;/simpleType>
     *         &lt;/element>
     *         &lt;element name="SIDL" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
     *         &lt;element name="SIDR" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
     *         &lt;element name="SPASZ" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
     *         &lt;element name="SPATRUNC" minOccurs="0">
     *           &lt;simpleType>
     *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
     *               &lt;enumeration value="R"/>
     *               &lt;enumeration value="S"/>
     *             &lt;/restriction>
     *           &lt;/simpleType>
     *         &lt;/element>
     *         &lt;element name="TRANSTAT" minOccurs="0">
     *           &lt;simpleType>
     *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
     *               &lt;enumeration value="N"/>
     *               &lt;enumeration value="Y"/>
     *             &lt;/restriction>
     *           &lt;/simpleType>
     *         &lt;/element>
     *         &lt;element name="WFI" minOccurs="0">
     *           &lt;simpleType>
     *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
     *               &lt;enumeration value="N"/>
     *               &lt;enumeration value="Y"/>
     *             &lt;/restriction>
     *           &lt;/simpleType>
     *         &lt;/element>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "aocmd",
        "_class",
        "cmtmode",
        "conv",
        "cpri",
        "dclwa",
        "dirroute",
        "editrtn",
        "edituc",
        "emhbsz",
        "exprtime",
        "fp",
        "inq",
        "lct",
        "lock",
        "lpri",
        "maxrgn",
        "msgtype",
        "msname",
        "npri",
        "parlim",
        "pgm",
        "plct",
        "plcttime",
        "recover",
        "remote",
        "resp",
        "segno",
        "segsz",
        "serial",
        "sidl",
        "sidr",
        "spasz",
        "spatrunc",
        "transtat",
        "wfi"
    })
    public static class SET {

        @XmlElement(name = "AOCMD")
        protected UpdateTran.SET.AocmdOptions aocmd;
        @XmlElement(name = "CLASS")
        protected Integer _class;
        @XmlElement(name = "CMTMODE")
        protected UpdateTran.SET.CmtmodeOptions cmtmode;
        @XmlElement(name = "CONV")
        protected UpdateTran.SET.ConvOptions conv;
        @XmlElement(name = "CPRI")
        protected Integer cpri;
        @XmlElement(name = "DCLWA")
        protected UpdateTran.SET.DclwaOptions dclwa;
        @XmlElement(name = "DIRROUTE")
        protected UpdateTran.SET.DirrouteOptions dirroute;
        @XmlElement(name = "EDITRTN")
        protected String editrtn;
        @XmlElement(name = "EDITUC")
        protected UpdateTran.SET.EditucOptions edituc;
        @XmlElement(name = "EMHBSZ")
        protected Integer emhbsz;
        @XmlElement(name = "EXPRTIME")
        protected Integer exprtime;
        @XmlElement(name = "FP")
        protected UpdateTran.SET.FpOptions fp;
        @XmlElement(name = "INQ")
        protected UpdateTran.SET.InqOptions inq;
        @XmlElement(name = "LCT")
        protected Integer lct;
        @XmlElement(name = "LOCK")
        protected UpdateTran.SET.LockOptions lock;
        @XmlElement(name = "LPRI")
        protected Integer lpri;
        @XmlElement(name = "MAXRGN")
        protected Integer maxrgn;
        @XmlElement(name = "MSGTYPE")
        protected UpdateTran.SET.MsgtypeOptions msgtype;
        @XmlElement(name = "MSNAME")
        protected String msname;
        @XmlElement(name = "NPRI")
        protected Integer npri;
        @XmlElement(name = "PARLIM")
        protected Integer parlim;
        @XmlElement(name = "PGM")
        protected String pgm;
        @XmlElement(name = "PLCT")
        protected Integer plct;
        @XmlElement(name = "PLCTTIME")
        protected Integer plcttime;
        @XmlElement(name = "RECOVER")
        protected UpdateTran.SET.RecoverOptions recover;
        @XmlElement(name = "REMOTE")
        protected UpdateTran.SET.RemoteOptions remote;
        @XmlElement(name = "RESP")
        protected UpdateTran.SET.RespOptions resp;
        @XmlElement(name = "SEGNO")
        protected Integer segno;
        @XmlElement(name = "SEGSZ")
        protected Integer segsz;
        @XmlElement(name = "SERIAL")
        protected UpdateTran.SET.SerialOptions serial;
        @XmlElement(name = "SIDL")
        protected Integer sidl;
        @XmlElement(name = "SIDR")
        protected Integer sidr;
        @XmlElement(name = "SPASZ")
        protected Integer spasz;
        @XmlElement(name = "SPATRUNC")
        protected UpdateTran.SET.SpatruncOptions spatrunc;
        @XmlElement(name = "TRANSTAT")
        protected UpdateTran.SET.TranstatOptions transtat;
        @XmlElement(name = "WFI")
        protected UpdateTran.SET.WfiOptions wfi;

        /**
         * Gets the value of the aocmd property.
         * 
         * @return
         *     possible object is
         *     {@link UpdateTran.SET.AocmdOptions }
         *     
         */
        public UpdateTran.SET.AocmdOptions getAOCMD() {
            return aocmd;
        }

        /**
         * Sets the value of the aocmd property.
         * 
         * @param value
         *     allowed object is
         *     {@link UpdateTran.SET.AocmdOptions }
         *     
         */
        public void setAOCMD(UpdateTran.SET.AocmdOptions value) {
            this.aocmd = value;
        }

        /**
         * Gets the value of the class property.
         * 
         * @return
         *     possible object is
         *     {@link Integer }
         *     
         */
        public Integer getCLASS() {
            return _class;
        }

        /**
         * Sets the value of the class property.
         * 
         * @param value
         *     allowed object is
         *     {@link Integer }
         *     
         */
        public void setCLASS(Integer value) {
            this._class = value;
        }

        /**
         * Gets the value of the cmtmode property.
         * 
         * @return
         *     possible object is
         *     {@link UpdateTran.SET.CmtmodeOptions }
         *     
         */
        public UpdateTran.SET.CmtmodeOptions getCMTMODE() {
            return cmtmode;
        }

        /**
         * Sets the value of the cmtmode property.
         * 
         * @param value
         *     allowed object is
         *     {@link UpdateTran.SET.CmtmodeOptions }
         *     
         */
        public void setCMTMODE(UpdateTran.SET.CmtmodeOptions value) {
            this.cmtmode = value;
        }

        /**
         * Gets the value of the conv property.
         * 
         * @return
         *     possible object is
         *     {@link UpdateTran.SET.ConvOptions }
         *     
         */
        public UpdateTran.SET.ConvOptions getCONV() {
            return conv;
        }

        /**
         * Sets the value of the conv property.
         * 
         * @param value
         *     allowed object is
         *     {@link UpdateTran.SET.ConvOptions }
         *     
         */
        public void setCONV(UpdateTran.SET.ConvOptions value) {
            this.conv = value;
        }

        /**
         * Gets the value of the cpri property.
         * 
         * @return
         *     possible object is
         *     {@link Integer }
         *     
         */
        public Integer getCPRI() {
            return cpri;
        }

        /**
         * Sets the value of the cpri property.
         * 
         * @param value
         *     allowed object is
         *     {@link Integer }
         *     
         */
        public void setCPRI(Integer value) {
            this.cpri = value;
        }

        /**
         * Gets the value of the dclwa property.
         * 
         * @return
         *     possible object is
         *     {@link UpdateTran.SET.DclwaOptions }
         *     
         */
        public UpdateTran.SET.DclwaOptions getDCLWA() {
            return dclwa;
        }

        /**
         * Sets the value of the dclwa property.
         * 
         * @param value
         *     allowed object is
         *     {@link UpdateTran.SET.DclwaOptions }
         *     
         */
        public void setDCLWA(UpdateTran.SET.DclwaOptions value) {
            this.dclwa = value;
        }

        /**
         * Gets the value of the dirroute property.
         * 
         * @return
         *     possible object is
         *     {@link UpdateTran.SET.DirrouteOptions }
         *     
         */
        public UpdateTran.SET.DirrouteOptions getDIRROUTE() {
            return dirroute;
        }

        /**
         * Sets the value of the dirroute property.
         * 
         * @param value
         *     allowed object is
         *     {@link UpdateTran.SET.DirrouteOptions }
         *     
         */
        public void setDIRROUTE(UpdateTran.SET.DirrouteOptions value) {
            this.dirroute = value;
        }

        /**
         * Gets the value of the editrtn property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getEDITRTN() {
            return editrtn;
        }

        /**
         * Sets the value of the editrtn property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setEDITRTN(String value) {
            this.editrtn = value;
        }

        /**
         * Gets the value of the edituc property.
         * 
         * @return
         *     possible object is
         *     {@link UpdateTran.SET.EditucOptions }
         *     
         */
        public UpdateTran.SET.EditucOptions getEDITUC() {
            return edituc;
        }

        /**
         * Sets the value of the edituc property.
         * 
         * @param value
         *     allowed object is
         *     {@link UpdateTran.SET.EditucOptions }
         *     
         */
        public void setEDITUC(UpdateTran.SET.EditucOptions value) {
            this.edituc = value;
        }

        /**
         * Gets the value of the emhbsz property.
         * 
         * @return
         *     possible object is
         *     {@link Integer }
         *     
         */
        public Integer getEMHBSZ() {
            return emhbsz;
        }

        /**
         * Sets the value of the emhbsz property.
         * 
         * @param value
         *     allowed object is
         *     {@link Integer }
         *     
         */
        public void setEMHBSZ(Integer value) {
            this.emhbsz = value;
        }

        /**
         * Gets the value of the exprtime property.
         * 
         * @return
         *     possible object is
         *     {@link Integer }
         *     
         */
        public Integer getEXPRTIME() {
            return exprtime;
        }

        /**
         * Sets the value of the exprtime property.
         * 
         * @param value
         *     allowed object is
         *     {@link Integer }
         *     
         */
        public void setEXPRTIME(Integer value) {
            this.exprtime = value;
        }

        /**
         * Gets the value of the fp property.
         * 
         * @return
         *     possible object is
         *     {@link UpdateTran.SET.FpOptions }
         *     
         */
        public UpdateTran.SET.FpOptions getFP() {
            return fp;
        }

        /**
         * Sets the value of the fp property.
         * 
         * @param value
         *     allowed object is
         *     {@link UpdateTran.SET.FpOptions }
         *     
         */
        public void setFP(UpdateTran.SET.FpOptions value) {
            this.fp = value;
        }

        /**
         * Gets the value of the inq property.
         * 
         * @return
         *     possible object is
         *     {@link UpdateTran.SET.InqOptions }
         *     
         */
        public UpdateTran.SET.InqOptions getINQ() {
            return inq;
        }

        /**
         * Sets the value of the inq property.
         * 
         * @param value
         *     allowed object is
         *     {@link UpdateTran.SET.InqOptions }
         *     
         */
        public void setINQ(UpdateTran.SET.InqOptions value) {
            this.inq = value;
        }

        /**
         * Gets the value of the lct property.
         * 
         * @return
         *     possible object is
         *     {@link Integer }
         *     
         */
        public Integer getLCT() {
            return lct;
        }

        /**
         * Sets the value of the lct property.
         * 
         * @param value
         *     allowed object is
         *     {@link Integer }
         *     
         */
        public void setLCT(Integer value) {
            this.lct = value;
        }

        /**
         * Gets the value of the lock property.
         * 
         * @return
         *     possible object is
         *     {@link UpdateTran.SET.LockOptions }
         *     
         */
        public UpdateTran.SET.LockOptions getLOCK() {
            return lock;
        }

        /**
         * Sets the value of the lock property.
         * 
         * @param value
         *     allowed object is
         *     {@link UpdateTran.SET.LockOptions }
         *     
         */
        public void setLOCK(UpdateTran.SET.LockOptions value) {
            this.lock = value;
        }

        /**
         * Gets the value of the lpri property.
         * 
         * @return
         *     possible object is
         *     {@link Integer }
         *     
         */
        public Integer getLPRI() {
            return lpri;
        }

        /**
         * Sets the value of the lpri property.
         * 
         * @param value
         *     allowed object is
         *     {@link Integer }
         *     
         */
        public void setLPRI(Integer value) {
            this.lpri = value;
        }

        /**
         * Gets the value of the maxrgn property.
         * 
         * @return
         *     possible object is
         *     {@link Integer }
         *     
         */
        public Integer getMAXRGN() {
            return maxrgn;
        }

        /**
         * Sets the value of the maxrgn property.
         * 
         * @param value
         *     allowed object is
         *     {@link Integer }
         *     
         */
        public void setMAXRGN(Integer value) {
            this.maxrgn = value;
        }

        /**
         * Gets the value of the msgtype property.
         * 
         * @return
         *     possible object is
         *     {@link UpdateTran.SET.MsgtypeOptions }
         *     
         */
        public UpdateTran.SET.MsgtypeOptions getMSGTYPE() {
            return msgtype;
        }

        /**
         * Sets the value of the msgtype property.
         * 
         * @param value
         *     allowed object is
         *     {@link UpdateTran.SET.MsgtypeOptions }
         *     
         */
        public void setMSGTYPE(UpdateTran.SET.MsgtypeOptions value) {
            this.msgtype = value;
        }

        /**
         * Gets the value of the msname property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getMSNAME() {
            return msname;
        }

        /**
         * Sets the value of the msname property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setMSNAME(String value) {
            this.msname = value;
        }

        /**
         * Gets the value of the npri property.
         * 
         * @return
         *     possible object is
         *     {@link Integer }
         *     
         */
        public Integer getNPRI() {
            return npri;
        }

        /**
         * Sets the value of the npri property.
         * 
         * @param value
         *     allowed object is
         *     {@link Integer }
         *     
         */
        public void setNPRI(Integer value) {
            this.npri = value;
        }

        /**
         * Gets the value of the parlim property.
         * 
         * @return
         *     possible object is
         *     {@link Integer }
         *     
         */
        public Integer getPARLIM() {
            return parlim;
        }

        /**
         * Sets the value of the parlim property.
         * 
         * @param value
         *     allowed object is
         *     {@link Integer }
         *     
         */
        public void setPARLIM(Integer value) {
            this.parlim = value;
        }

        /**
         * Gets the value of the pgm property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getPGM() {
            return pgm;
        }

        /**
         * Sets the value of the pgm property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setPGM(String value) {
            this.pgm = value;
        }

        /**
         * Gets the value of the plct property.
         * 
         * @return
         *     possible object is
         *     {@link Integer }
         *     
         */
        public Integer getPLCT() {
            return plct;
        }

        /**
         * Sets the value of the plct property.
         * 
         * @param value
         *     allowed object is
         *     {@link Integer }
         *     
         */
        public void setPLCT(Integer value) {
            this.plct = value;
        }

        /**
         * Gets the value of the plcttime property.
         * 
         * @return
         *     possible object is
         *     {@link Integer }
         *     
         */
        public Integer getPLCTTIME() {
            return plcttime;
        }

        /**
         * Sets the value of the plcttime property.
         * 
         * @param value
         *     allowed object is
         *     {@link Integer }
         *     
         */
        public void setPLCTTIME(Integer value) {
            this.plcttime = value;
        }

        /**
         * Gets the value of the recover property.
         * 
         * @return
         *     possible object is
         *     {@link UpdateTran.SET.RecoverOptions }
         *     
         */
        public UpdateTran.SET.RecoverOptions getRECOVER() {
            return recover;
        }

        /**
         * Sets the value of the recover property.
         * 
         * @param value
         *     allowed object is
         *     {@link UpdateTran.SET.RecoverOptions }
         *     
         */
        public void setRECOVER(UpdateTran.SET.RecoverOptions value) {
            this.recover = value;
        }

        /**
         * Gets the value of the remote property.
         * 
         * @return
         *     possible object is
         *     {@link UpdateTran.SET.RemoteOptions }
         *     
         */
        public UpdateTran.SET.RemoteOptions getREMOTE() {
            return remote;
        }

        /**
         * Sets the value of the remote property.
         * 
         * @param value
         *     allowed object is
         *     {@link UpdateTran.SET.RemoteOptions }
         *     
         */
        public void setREMOTE(UpdateTran.SET.RemoteOptions value) {
            this.remote = value;
        }

        /**
         * Gets the value of the resp property.
         * 
         * @return
         *     possible object is
         *     {@link UpdateTran.SET.RespOptions }
         *     
         */
        public UpdateTran.SET.RespOptions getRESP() {
            return resp;
        }

        /**
         * Sets the value of the resp property.
         * 
         * @param value
         *     allowed object is
         *     {@link UpdateTran.SET.RespOptions }
         *     
         */
        public void setRESP(UpdateTran.SET.RespOptions value) {
            this.resp = value;
        }

        /**
         * Gets the value of the segno property.
         * 
         * @return
         *     possible object is
         *     {@link Integer }
         *     
         */
        public Integer getSEGNO() {
            return segno;
        }

        /**
         * Sets the value of the segno property.
         * 
         * @param value
         *     allowed object is
         *     {@link Integer }
         *     
         */
        public void setSEGNO(Integer value) {
            this.segno = value;
        }

        /**
         * Gets the value of the segsz property.
         * 
         * @return
         *     possible object is
         *     {@link Integer }
         *     
         */
        public Integer getSEGSZ() {
            return segsz;
        }

        /**
         * Sets the value of the segsz property.
         * 
         * @param value
         *     allowed object is
         *     {@link Integer }
         *     
         */
        public void setSEGSZ(Integer value) {
            this.segsz = value;
        }

        /**
         * Gets the value of the serial property.
         * 
         * @return
         *     possible object is
         *     {@link UpdateTran.SET.SerialOptions }
         *     
         */
        public UpdateTran.SET.SerialOptions getSERIAL() {
            return serial;
        }

        /**
         * Sets the value of the serial property.
         * 
         * @param value
         *     allowed object is
         *     {@link UpdateTran.SET.SerialOptions }
         *     
         */
        public void setSERIAL(UpdateTran.SET.SerialOptions value) {
            this.serial = value;
        }

        /**
         * Gets the value of the sidl property.
         * 
         * @return
         *     possible object is
         *     {@link Integer }
         *     
         */
        public Integer getSIDL() {
            return sidl;
        }

        /**
         * Sets the value of the sidl property.
         * 
         * @param value
         *     allowed object is
         *     {@link Integer }
         *     
         */
        public void setSIDL(Integer value) {
            this.sidl = value;
        }

        /**
         * Gets the value of the sidr property.
         * 
         * @return
         *     possible object is
         *     {@link Integer }
         *     
         */
        public Integer getSIDR() {
            return sidr;
        }

        /**
         * Sets the value of the sidr property.
         * 
         * @param value
         *     allowed object is
         *     {@link Integer }
         *     
         */
        public void setSIDR(Integer value) {
            this.sidr = value;
        }

        /**
         * Gets the value of the spasz property.
         * 
         * @return
         *     possible object is
         *     {@link Integer }
         *     
         */
        public Integer getSPASZ() {
            return spasz;
        }

        /**
         * Sets the value of the spasz property.
         * 
         * @param value
         *     allowed object is
         *     {@link Integer }
         *     
         */
        public void setSPASZ(Integer value) {
            this.spasz = value;
        }

        /**
         * Gets the value of the spatrunc property.
         * 
         * @return
         *     possible object is
         *     {@link UpdateTran.SET.SpatruncOptions }
         *     
         */
        public UpdateTran.SET.SpatruncOptions getSPATRUNC() {
            return spatrunc;
        }

        /**
         * Sets the value of the spatrunc property.
         * 
         * @param value
         *     allowed object is
         *     {@link UpdateTran.SET.SpatruncOptions }
         *     
         */
        public void setSPATRUNC(UpdateTran.SET.SpatruncOptions value) {
            this.spatrunc = value;
        }

        /**
         * Gets the value of the transtat property.
         * 
         * @return
         *     possible object is
         *     {@link UpdateTran.SET.TranstatOptions }
         *     
         */
        public UpdateTran.SET.TranstatOptions getTRANSTAT() {
            return transtat;
        }

        /**
         * Sets the value of the transtat property.
         * 
         * @param value
         *     allowed object is
         *     {@link UpdateTran.SET.TranstatOptions }
         *     
         */
        public void setTRANSTAT(UpdateTran.SET.TranstatOptions value) {
            this.transtat = value;
        }

        /**
         * Gets the value of the wfi property.
         * 
         * @return
         *     possible object is
         *     {@link UpdateTran.SET.WfiOptions }
         *     
         */
        public UpdateTran.SET.WfiOptions getWFI() {
            return wfi;
        }

        /**
         * Sets the value of the wfi property.
         * 
         * @param value
         *     allowed object is
         *     {@link UpdateTran.SET.WfiOptions }
         *     
         */
        public void setWFI(UpdateTran.SET.WfiOptions value) {
            this.wfi = value;
        }


        /**
         * <p>Java class for null.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * <p>
         * <pre>
         * &lt;simpleType>
         *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
         *     &lt;enumeration value="CMD"/>
         *     &lt;enumeration value="N"/>
         *     &lt;enumeration value="TRAN"/>
         *     &lt;enumeration value="Y"/>
         *   &lt;/restriction>
         * &lt;/simpleType>
         * </pre>
         * 
         */
        @XmlType(name = "")
        @XmlEnum
        public enum AocmdOptions {

            CMD,
            N,
            TRAN,
            Y;

            public String value() {
                return name();
            }

            public static UpdateTran.SET.AocmdOptions fromValue(String v) {
                return valueOf(v);
            }

        }


        /**
         * <p>Java class for null.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * <p>
         * <pre>
         * &lt;simpleType>
         *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
         *     &lt;enumeration value="MULT"/>
         *     &lt;enumeration value="SNGL"/>
         *   &lt;/restriction>
         * &lt;/simpleType>
         * </pre>
         * 
         */
        @XmlType(name = "")
        @XmlEnum
        public enum CmtmodeOptions {

            MULT,
            SNGL;

            public String value() {
                return name();
            }

            public static UpdateTran.SET.CmtmodeOptions fromValue(String v) {
                return valueOf(v);
            }

        }


        /**
         * <p>Java class for null.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * <p>
         * <pre>
         * &lt;simpleType>
         *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
         *     &lt;enumeration value="N"/>
         *     &lt;enumeration value="Y"/>
         *   &lt;/restriction>
         * &lt;/simpleType>
         * </pre>
         * 
         */
        @XmlType(name = "")
        @XmlEnum
        public enum ConvOptions {

            N,
            Y;

            public String value() {
                return name();
            }

            public static UpdateTran.SET.ConvOptions fromValue(String v) {
                return valueOf(v);
            }

        }


        /**
         * <p>Java class for null.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * <p>
         * <pre>
         * &lt;simpleType>
         *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
         *     &lt;enumeration value="N"/>
         *     &lt;enumeration value="Y"/>
         *   &lt;/restriction>
         * &lt;/simpleType>
         * </pre>
         * 
         */
        @XmlType(name = "")
        @XmlEnum
        public enum DclwaOptions {

            N,
            Y;

            public String value() {
                return name();
            }

            public static UpdateTran.SET.DclwaOptions fromValue(String v) {
                return valueOf(v);
            }

        }


        /**
         * <p>Java class for null.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * <p>
         * <pre>
         * &lt;simpleType>
         *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
         *     &lt;enumeration value="N"/>
         *     &lt;enumeration value="Y"/>
         *   &lt;/restriction>
         * &lt;/simpleType>
         * </pre>
         * 
         */
        @XmlType(name = "")
        @XmlEnum
        public enum DirrouteOptions {

            N,
            Y;

            public String value() {
                return name();
            }

            public static UpdateTran.SET.DirrouteOptions fromValue(String v) {
                return valueOf(v);
            }

        }


        /**
         * <p>Java class for null.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * <p>
         * <pre>
         * &lt;simpleType>
         *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
         *     &lt;enumeration value="N"/>
         *     &lt;enumeration value="Y"/>
         *   &lt;/restriction>
         * &lt;/simpleType>
         * </pre>
         * 
         */
        @XmlType(name = "")
        @XmlEnum
        public enum EditucOptions {

            N,
            Y;

            public String value() {
                return name();
            }

            public static UpdateTran.SET.EditucOptions fromValue(String v) {
                return valueOf(v);
            }

        }


        /**
         * <p>Java class for null.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * <p>
         * <pre>
         * &lt;simpleType>
         *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
         *     &lt;enumeration value="E"/>
         *     &lt;enumeration value="N"/>
         *     &lt;enumeration value="P"/>
         *   &lt;/restriction>
         * &lt;/simpleType>
         * </pre>
         * 
         */
        @XmlType(name = "")
        @XmlEnum
        public enum FpOptions {

            E,
            N,
            P;

            public String value() {
                return name();
            }

            public static UpdateTran.SET.FpOptions fromValue(String v) {
                return valueOf(v);
            }

        }


        /**
         * <p>Java class for null.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * <p>
         * <pre>
         * &lt;simpleType>
         *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
         *     &lt;enumeration value="N"/>
         *     &lt;enumeration value="Y"/>
         *   &lt;/restriction>
         * &lt;/simpleType>
         * </pre>
         * 
         */
        @XmlType(name = "")
        @XmlEnum
        public enum InqOptions {

            N,
            Y;

            public String value() {
                return name();
            }

            public static UpdateTran.SET.InqOptions fromValue(String v) {
                return valueOf(v);
            }

        }


        /**
         * <p>Java class for null.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * <p>
         * <pre>
         * &lt;simpleType>
         *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
         *     &lt;enumeration value="ON"/>
         *     &lt;enumeration value="OFF"/>
         *   &lt;/restriction>
         * &lt;/simpleType>
         * </pre>
         * 
         */
        @XmlType(name = "")
        @XmlEnum
        public enum LockOptions {

            ON,
            OFF;

            public String value() {
                return name();
            }

            public static UpdateTran.SET.LockOptions fromValue(String v) {
                return valueOf(v);
            }

        }


        /**
         * <p>Java class for null.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * <p>
         * <pre>
         * &lt;simpleType>
         *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
         *     &lt;enumeration value="MULTSEG"/>
         *     &lt;enumeration value="SNGLSEG"/>
         *   &lt;/restriction>
         * &lt;/simpleType>
         * </pre>
         * 
         */
        @XmlType(name = "")
        @XmlEnum
        public enum MsgtypeOptions {

            MULTSEG,
            SNGLSEG;

            public String value() {
                return name();
            }

            public static UpdateTran.SET.MsgtypeOptions fromValue(String v) {
                return valueOf(v);
            }

        }


        /**
         * <p>Java class for null.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * <p>
         * <pre>
         * &lt;simpleType>
         *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
         *     &lt;enumeration value="N"/>
         *     &lt;enumeration value="Y"/>
         *   &lt;/restriction>
         * &lt;/simpleType>
         * </pre>
         * 
         */
        @XmlType(name = "")
        @XmlEnum
        public enum RecoverOptions {

            N,
            Y;

            public String value() {
                return name();
            }

            public static UpdateTran.SET.RecoverOptions fromValue(String v) {
                return valueOf(v);
            }

        }


        /**
         * <p>Java class for null.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * <p>
         * <pre>
         * &lt;simpleType>
         *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
         *     &lt;enumeration value="N"/>
         *     &lt;enumeration value="Y"/>
         *   &lt;/restriction>
         * &lt;/simpleType>
         * </pre>
         * 
         */
        @XmlType(name = "")
        @XmlEnum
        public enum RemoteOptions {

            N,
            Y;

            public String value() {
                return name();
            }

            public static UpdateTran.SET.RemoteOptions fromValue(String v) {
                return valueOf(v);
            }

        }


        /**
         * <p>Java class for null.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * <p>
         * <pre>
         * &lt;simpleType>
         *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
         *     &lt;enumeration value="N"/>
         *     &lt;enumeration value="Y"/>
         *   &lt;/restriction>
         * &lt;/simpleType>
         * </pre>
         * 
         */
        @XmlType(name = "")
        @XmlEnum
        public enum RespOptions {

            N,
            Y;

            public String value() {
                return name();
            }

            public static UpdateTran.SET.RespOptions fromValue(String v) {
                return valueOf(v);
            }

        }


        /**
         * <p>Java class for null.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * <p>
         * <pre>
         * &lt;simpleType>
         *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
         *     &lt;enumeration value="N"/>
         *     &lt;enumeration value="Y"/>
         *   &lt;/restriction>
         * &lt;/simpleType>
         * </pre>
         * 
         */
        @XmlType(name = "")
        @XmlEnum
        public enum SerialOptions {

            N,
            Y;

            public String value() {
                return name();
            }

            public static UpdateTran.SET.SerialOptions fromValue(String v) {
                return valueOf(v);
            }

        }


        /**
         * <p>Java class for null.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * <p>
         * <pre>
         * &lt;simpleType>
         *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
         *     &lt;enumeration value="R"/>
         *     &lt;enumeration value="S"/>
         *   &lt;/restriction>
         * &lt;/simpleType>
         * </pre>
         * 
         */
        @XmlType(name = "")
        @XmlEnum
        public enum SpatruncOptions {

            R,
            S;

            public String value() {
                return name();
            }

            public static UpdateTran.SET.SpatruncOptions fromValue(String v) {
                return valueOf(v);
            }

        }


        /**
         * <p>Java class for null.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * <p>
         * <pre>
         * &lt;simpleType>
         *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
         *     &lt;enumeration value="N"/>
         *     &lt;enumeration value="Y"/>
         *   &lt;/restriction>
         * &lt;/simpleType>
         * </pre>
         * 
         */
        @XmlType(name = "")
        @XmlEnum
        public enum TranstatOptions {

            N,
            Y;

            public String value() {
                return name();
            }

            public static UpdateTran.SET.TranstatOptions fromValue(String v) {
                return valueOf(v);
            }

        }


        /**
         * <p>Java class for null.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * <p>
         * <pre>
         * &lt;simpleType>
         *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
         *     &lt;enumeration value="N"/>
         *     &lt;enumeration value="Y"/>
         *   &lt;/restriction>
         * &lt;/simpleType>
         * </pre>
         * 
         */
        @XmlType(name = "")
        @XmlEnum
        public enum WfiOptions {

            N,
            Y;

            public String value() {
                return name();
            }

            public static UpdateTran.SET.WfiOptions fromValue(String v) {
                return valueOf(v);
            }

        }

    }


    /**
     * <p>Java class for null.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * <p>
     * <pre>
     * &lt;simpleType>
     *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
     *     &lt;enumeration value="Q"/>
     *     &lt;enumeration value="SCHD"/>
     *     &lt;enumeration value="SUSPEND"/>
     *     &lt;enumeration value="TRACE"/>
     *   &lt;/restriction>
     * &lt;/simpleType>
     * </pre>
     * 
     */
    @XmlType(name = "")
    @XmlEnum
    public enum StartOptions {

        Q,
        SCHD,
        SUSPEND,
        TRACE;

        public String value() {
            return name();
        }

        public static UpdateTran.StartOptions fromValue(String v) {
            return valueOf(v);
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="START" maxOccurs="unbounded" minOccurs="0">
     *           &lt;simpleType>
     *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
     *               &lt;enumeration value="Q"/>
     *               &lt;enumeration value="SCHD"/>
     *               &lt;enumeration value="SUSPEND"/>
     *               &lt;enumeration value="TRACE"/>
     *             &lt;/restriction>
     *           &lt;/simpleType>
     *         &lt;/element>
     *         &lt;element name="STOP" maxOccurs="unbounded" minOccurs="0">
     *           &lt;simpleType>
     *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
     *               &lt;enumeration value="Q"/>
     *               &lt;enumeration value="SCHD"/>
     *               &lt;enumeration value="TRACE"/>
     *             &lt;/restriction>
     *           &lt;/simpleType>
     *         &lt;/element>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "start",
        "stop"
    })
    public static class STARTSTOP {

        @XmlElement(name = "START")
        protected List<UpdateTran.STARTSTOP.StartOptions> start;
        @XmlElement(name = "STOP")
        protected List<UpdateTran.STARTSTOP.StopOptions> stop;

        /**
         * Gets the value of the start property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the start property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getSTART().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link UpdateTran.STARTSTOP.StartOptions }
         * 
         * 
         */
        public List<UpdateTran.STARTSTOP.StartOptions> getSTART() {
            if (start == null) {
                start = new ArrayList<UpdateTran.STARTSTOP.StartOptions>();
            }
            return this.start;
        }

        /**
         * Gets the value of the stop property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the stop property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getSTOP().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link UpdateTran.STARTSTOP.StopOptions }
         * 
         * 
         */
        public List<UpdateTran.STARTSTOP.StopOptions> getSTOP() {
            if (stop == null) {
                stop = new ArrayList<UpdateTran.STARTSTOP.StopOptions>();
            }
            return this.stop;
        }


        /**
         * <p>Java class for null.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * <p>
         * <pre>
         * &lt;simpleType>
         *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
         *     &lt;enumeration value="Q"/>
         *     &lt;enumeration value="SCHD"/>
         *     &lt;enumeration value="SUSPEND"/>
         *     &lt;enumeration value="TRACE"/>
         *   &lt;/restriction>
         * &lt;/simpleType>
         * </pre>
         * 
         */
        @XmlType(name = "")
        @XmlEnum
        public enum StartOptions {

            Q,
            SCHD,
            SUSPEND,
            TRACE;

            public String value() {
                return name();
            }

            public static UpdateTran.STARTSTOP.StartOptions fromValue(String v) {
                return valueOf(v);
            }

        }


        /**
         * <p>Java class for null.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * <p>
         * <pre>
         * &lt;simpleType>
         *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
         *     &lt;enumeration value="Q"/>
         *     &lt;enumeration value="SCHD"/>
         *     &lt;enumeration value="TRACE"/>
         *   &lt;/restriction>
         * &lt;/simpleType>
         * </pre>
         * 
         */
        @XmlType(name = "")
        @XmlEnum
        public enum StopOptions {

            Q,
            SCHD,
            TRACE;

            public String value() {
                return name();
            }

            public static UpdateTran.STARTSTOP.StopOptions fromValue(String v) {
                return valueOf(v);
            }

        }

    }


    /**
     * <p>Java class for null.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * <p>
     * <pre>
     * &lt;simpleType>
     *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
     *     &lt;enumeration value="Q"/>
     *     &lt;enumeration value="SCHD"/>
     *     &lt;enumeration value="TRACE"/>
     *   &lt;/restriction>
     * &lt;/simpleType>
     * </pre>
     * 
     */
    @XmlType(name = "")
    @XmlEnum
    public enum StopOptions {

        Q,
        SCHD,
        TRACE;

        public String value() {
            return name();
        }

        public static UpdateTran.StopOptions fromValue(String v) {
            return valueOf(v);
        }

    }

}
