/**
 *  Copyright IBM Corporation 2018, 2019
 */


// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.12.04 at 10:33:16 PM PST 
//


package commands.update.pgm;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for UpdatePgm complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="UpdatePgm">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="NAME" type="{commands/update/pgm}nameOptions" maxOccurs="unbounded"/>
 *         &lt;choice>
 *           &lt;element name="START" maxOccurs="unbounded" minOccurs="0">
 *             &lt;simpleType>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                 &lt;enumeration value="SCHD"/>
 *                 &lt;enumeration value="TRACE"/>
 *                 &lt;enumeration value="REFRESH"/>
 *               &lt;/restriction>
 *             &lt;/simpleType>
 *           &lt;/element>
 *           &lt;element name="STOP" maxOccurs="unbounded" minOccurs="0">
 *             &lt;simpleType>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                 &lt;enumeration value="SCHD"/>
 *                 &lt;enumeration value="TRACE"/>
 *               &lt;/restriction>
 *             &lt;/simpleType>
 *           &lt;/element>
 *           &lt;element name="STARTSTOP" maxOccurs="unbounded" minOccurs="0">
 *             &lt;complexType>
 *               &lt;complexContent>
 *                 &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                   &lt;sequence>
 *                     &lt;element name="START" maxOccurs="unbounded" minOccurs="0">
 *                       &lt;simpleType>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                           &lt;enumeration value="SCHD"/>
 *                           &lt;enumeration value="TRACE"/>
 *                           &lt;enumeration value="REFRESH"/>
 *                         &lt;/restriction>
 *                       &lt;/simpleType>
 *                     &lt;/element>
 *                     &lt;element name="STOP" maxOccurs="unbounded" minOccurs="0">
 *                       &lt;simpleType>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                           &lt;enumeration value="SCHD"/>
 *                           &lt;enumeration value="TRACE"/>
 *                         &lt;/restriction>
 *                       &lt;/simpleType>
 *                     &lt;/element>
 *                   &lt;/sequence>
 *                 &lt;/restriction>
 *               &lt;/complexContent>
 *             &lt;/complexType>
 *           &lt;/element>
 *           &lt;element name="SET" minOccurs="0">
 *             &lt;complexType>
 *               &lt;complexContent>
 *                 &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                   &lt;sequence>
 *                     &lt;element name="BMPTYPE" minOccurs="0">
 *                       &lt;simpleType>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                           &lt;enumeration value="Y"/>
 *                           &lt;enumeration value="N"/>
 *                         &lt;/restriction>
 *                       &lt;/simpleType>
 *                     &lt;/element>
 *                     &lt;element name="DOPT" minOccurs="0">
 *                       &lt;simpleType>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                           &lt;enumeration value="Y"/>
 *                           &lt;enumeration value="N"/>
 *                         &lt;/restriction>
 *                       &lt;/simpleType>
 *                     &lt;/element>
 *                     &lt;element name="FP" minOccurs="0">
 *                       &lt;simpleType>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                           &lt;enumeration value="E"/>
 *                           &lt;enumeration value="N"/>
 *                         &lt;/restriction>
 *                       &lt;/simpleType>
 *                     &lt;/element>
 *                     &lt;element name="GPSB" minOccurs="0">
 *                       &lt;simpleType>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                           &lt;enumeration value="Y"/>
 *                           &lt;enumeration value="N"/>
 *                         &lt;/restriction>
 *                       &lt;/simpleType>
 *                     &lt;/element>
 *                     &lt;element name="LANG" minOccurs="0">
 *                       &lt;simpleType>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                           &lt;enumeration value="ASSEM"/>
 *                           &lt;enumeration value="COBOL"/>
 *                           &lt;enumeration value="JAVA"/>
 *                           &lt;enumeration value="PASCAL"/>
 *                           &lt;enumeration value="PLI"/>
 *                         &lt;/restriction>
 *                       &lt;/simpleType>
 *                     &lt;/element>
 *                     &lt;element name="LOCK" minOccurs="0">
 *                       &lt;simpleType>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                           &lt;enumeration value="ON"/>
 *                           &lt;enumeration value="OFF"/>
 *                         &lt;/restriction>
 *                       &lt;/simpleType>
 *                     &lt;/element>
 *                     &lt;element name="RESIDENT" minOccurs="0">
 *                       &lt;simpleType>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                           &lt;enumeration value="N"/>
 *                           &lt;enumeration value="Y"/>
 *                         &lt;/restriction>
 *                       &lt;/simpleType>
 *                     &lt;/element>
 *                     &lt;element name="SCHDTYPE" minOccurs="0">
 *                       &lt;simpleType>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                           &lt;enumeration value="PARALLEL"/>
 *                           &lt;enumeration value="SERIAL"/>
 *                         &lt;/restriction>
 *                       &lt;/simpleType>
 *                     &lt;/element>
 *                     &lt;element name="TRANSTAT" minOccurs="0">
 *                       &lt;simpleType>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                           &lt;enumeration value="N"/>
 *                           &lt;enumeration value="Y"/>
 *                         &lt;/restriction>
 *                       &lt;/simpleType>
 *                     &lt;/element>
 *                   &lt;/sequence>
 *                 &lt;/restriction>
 *               &lt;/complexContent>
 *             &lt;/complexType>
 *           &lt;/element>
 *         &lt;/choice>
 *         &lt;element name="OPTION" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;enumeration value="ALLRSP"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "UpdatePgm", propOrder = {
    "name",
    "start",
    "stop",
    "startstop",
    "set",
    "option"
})
public class UpdatePgm {

    @XmlElement(name = "NAME", required = true)
    protected List<String> name;
    @XmlElement(name = "START")
    protected List<UpdatePgm.StartOptions> start;
    @XmlElement(name = "STOP")
    protected List<UpdatePgm.StopOptions> stop;
    @XmlElement(name = "STARTSTOP")
    protected List<UpdatePgm.STARTSTOP> startstop;
    @XmlElement(name = "SET")
    protected UpdatePgm.SET set;
    @XmlElement(name = "OPTION")
    protected UpdatePgm.OptionOptions option;

    /**
     * Gets the value of the name property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the name property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getNAME().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     * 
     * 
     */
    public List<String> getNAME() {
        if (name == null) {
            name = new ArrayList<String>();
        }
        return this.name;
    }

    /**
     * Gets the value of the start property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the start property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getSTART().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link UpdatePgm.StartOptions }
     * 
     * 
     */
    public List<UpdatePgm.StartOptions> getSTART() {
        if (start == null) {
            start = new ArrayList<UpdatePgm.StartOptions>();
        }
        return this.start;
    }

    /**
     * Gets the value of the stop property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the stop property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getSTOP().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link UpdatePgm.StopOptions }
     * 
     * 
     */
    public List<UpdatePgm.StopOptions> getSTOP() {
        if (stop == null) {
            stop = new ArrayList<UpdatePgm.StopOptions>();
        }
        return this.stop;
    }

    /**
     * Gets the value of the startstop property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the startstop property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getSTARTSTOP().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link UpdatePgm.STARTSTOP }
     * 
     * 
     */
    public List<UpdatePgm.STARTSTOP> getSTARTSTOP() {
        if (startstop == null) {
            startstop = new ArrayList<UpdatePgm.STARTSTOP>();
        }
        return this.startstop;
    }

    /**
     * Gets the value of the set property.
     * 
     * @return
     *     possible object is
     *     {@link UpdatePgm.SET }
     *     
     */
    public UpdatePgm.SET getSET() {
        return set;
    }

    /**
     * Sets the value of the set property.
     * 
     * @param value
     *     allowed object is
     *     {@link UpdatePgm.SET }
     *     
     */
    public void setSET(UpdatePgm.SET value) {
        this.set = value;
    }

    /**
     * Gets the value of the option property.
     * 
     * @return
     *     possible object is
     *     {@link UpdatePgm.OptionOptions }
     *     
     */
    public UpdatePgm.OptionOptions getOPTION() {
        return option;
    }

    /**
     * Sets the value of the option property.
     * 
     * @param value
     *     allowed object is
     *     {@link UpdatePgm.OptionOptions }
     *     
     */
    public void setOPTION(UpdatePgm.OptionOptions value) {
        this.option = value;
    }


    /**
     * <p>Java class for null.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * <p>
     * <pre>
     * &lt;simpleType>
     *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
     *     &lt;enumeration value="ALLRSP"/>
     *   &lt;/restriction>
     * &lt;/simpleType>
     * </pre>
     * 
     */
    @XmlType(name = "")
    @XmlEnum
    public enum OptionOptions {

        ALLRSP;

        public String value() {
            return name();
        }

        public static UpdatePgm.OptionOptions fromValue(String v) {
            return valueOf(v);
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="BMPTYPE" minOccurs="0">
     *           &lt;simpleType>
     *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
     *               &lt;enumeration value="Y"/>
     *               &lt;enumeration value="N"/>
     *             &lt;/restriction>
     *           &lt;/simpleType>
     *         &lt;/element>
     *         &lt;element name="DOPT" minOccurs="0">
     *           &lt;simpleType>
     *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
     *               &lt;enumeration value="Y"/>
     *               &lt;enumeration value="N"/>
     *             &lt;/restriction>
     *           &lt;/simpleType>
     *         &lt;/element>
     *         &lt;element name="FP" minOccurs="0">
     *           &lt;simpleType>
     *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
     *               &lt;enumeration value="E"/>
     *               &lt;enumeration value="N"/>
     *             &lt;/restriction>
     *           &lt;/simpleType>
     *         &lt;/element>
     *         &lt;element name="GPSB" minOccurs="0">
     *           &lt;simpleType>
     *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
     *               &lt;enumeration value="Y"/>
     *               &lt;enumeration value="N"/>
     *             &lt;/restriction>
     *           &lt;/simpleType>
     *         &lt;/element>
     *         &lt;element name="LANG" minOccurs="0">
     *           &lt;simpleType>
     *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
     *               &lt;enumeration value="ASSEM"/>
     *               &lt;enumeration value="COBOL"/>
     *               &lt;enumeration value="JAVA"/>
     *               &lt;enumeration value="PASCAL"/>
     *               &lt;enumeration value="PLI"/>
     *             &lt;/restriction>
     *           &lt;/simpleType>
     *         &lt;/element>
     *         &lt;element name="LOCK" minOccurs="0">
     *           &lt;simpleType>
     *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
     *               &lt;enumeration value="ON"/>
     *               &lt;enumeration value="OFF"/>
     *             &lt;/restriction>
     *           &lt;/simpleType>
     *         &lt;/element>
     *         &lt;element name="RESIDENT" minOccurs="0">
     *           &lt;simpleType>
     *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
     *               &lt;enumeration value="N"/>
     *               &lt;enumeration value="Y"/>
     *             &lt;/restriction>
     *           &lt;/simpleType>
     *         &lt;/element>
     *         &lt;element name="SCHDTYPE" minOccurs="0">
     *           &lt;simpleType>
     *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
     *               &lt;enumeration value="PARALLEL"/>
     *               &lt;enumeration value="SERIAL"/>
     *             &lt;/restriction>
     *           &lt;/simpleType>
     *         &lt;/element>
     *         &lt;element name="TRANSTAT" minOccurs="0">
     *           &lt;simpleType>
     *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
     *               &lt;enumeration value="N"/>
     *               &lt;enumeration value="Y"/>
     *             &lt;/restriction>
     *           &lt;/simpleType>
     *         &lt;/element>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "bmptype",
        "dopt",
        "fp",
        "gpsb",
        "lang",
        "lock",
        "resident",
        "schdtype",
        "transtat"
    })
    public static class SET {

        @XmlElement(name = "BMPTYPE")
        protected UpdatePgm.SET.BmptypeOptions bmptype;
        @XmlElement(name = "DOPT")
        protected UpdatePgm.SET.DoptOptions dopt;
        @XmlElement(name = "FP")
        protected UpdatePgm.SET.FpOptions fp;
        @XmlElement(name = "GPSB")
        protected UpdatePgm.SET.GpsbOptions gpsb;
        @XmlElement(name = "LANG")
        protected UpdatePgm.SET.LangOptions lang;
        @XmlElement(name = "LOCK")
        protected UpdatePgm.SET.LockOptions lock;
        @XmlElement(name = "RESIDENT")
        protected UpdatePgm.SET.ResidentOptions resident;
        @XmlElement(name = "SCHDTYPE")
        protected UpdatePgm.SET.SchdtypeOptions schdtype;
        @XmlElement(name = "TRANSTAT")
        protected UpdatePgm.SET.TranstatOptions transtat;

        /**
         * Gets the value of the bmptype property.
         * 
         * @return
         *     possible object is
         *     {@link UpdatePgm.SET.BmptypeOptions }
         *     
         */
        public UpdatePgm.SET.BmptypeOptions getBMPTYPE() {
            return bmptype;
        }

        /**
         * Sets the value of the bmptype property.
         * 
         * @param value
         *     allowed object is
         *     {@link UpdatePgm.SET.BmptypeOptions }
         *     
         */
        public void setBMPTYPE(UpdatePgm.SET.BmptypeOptions value) {
            this.bmptype = value;
        }

        /**
         * Gets the value of the dopt property.
         * 
         * @return
         *     possible object is
         *     {@link UpdatePgm.SET.DoptOptions }
         *     
         */
        public UpdatePgm.SET.DoptOptions getDOPT() {
            return dopt;
        }

        /**
         * Sets the value of the dopt property.
         * 
         * @param value
         *     allowed object is
         *     {@link UpdatePgm.SET.DoptOptions }
         *     
         */
        public void setDOPT(UpdatePgm.SET.DoptOptions value) {
            this.dopt = value;
        }

        /**
         * Gets the value of the fp property.
         * 
         * @return
         *     possible object is
         *     {@link UpdatePgm.SET.FpOptions }
         *     
         */
        public UpdatePgm.SET.FpOptions getFP() {
            return fp;
        }

        /**
         * Sets the value of the fp property.
         * 
         * @param value
         *     allowed object is
         *     {@link UpdatePgm.SET.FpOptions }
         *     
         */
        public void setFP(UpdatePgm.SET.FpOptions value) {
            this.fp = value;
        }

        /**
         * Gets the value of the gpsb property.
         * 
         * @return
         *     possible object is
         *     {@link UpdatePgm.SET.GpsbOptions }
         *     
         */
        public UpdatePgm.SET.GpsbOptions getGPSB() {
            return gpsb;
        }

        /**
         * Sets the value of the gpsb property.
         * 
         * @param value
         *     allowed object is
         *     {@link UpdatePgm.SET.GpsbOptions }
         *     
         */
        public void setGPSB(UpdatePgm.SET.GpsbOptions value) {
            this.gpsb = value;
        }

        /**
         * Gets the value of the lang property.
         * 
         * @return
         *     possible object is
         *     {@link UpdatePgm.SET.LangOptions }
         *     
         */
        public UpdatePgm.SET.LangOptions getLANG() {
            return lang;
        }

        /**
         * Sets the value of the lang property.
         * 
         * @param value
         *     allowed object is
         *     {@link UpdatePgm.SET.LangOptions }
         *     
         */
        public void setLANG(UpdatePgm.SET.LangOptions value) {
            this.lang = value;
        }

        /**
         * Gets the value of the lock property.
         * 
         * @return
         *     possible object is
         *     {@link UpdatePgm.SET.LockOptions }
         *     
         */
        public UpdatePgm.SET.LockOptions getLOCK() {
            return lock;
        }

        /**
         * Sets the value of the lock property.
         * 
         * @param value
         *     allowed object is
         *     {@link UpdatePgm.SET.LockOptions }
         *     
         */
        public void setLOCK(UpdatePgm.SET.LockOptions value) {
            this.lock = value;
        }

        /**
         * Gets the value of the resident property.
         * 
         * @return
         *     possible object is
         *     {@link UpdatePgm.SET.ResidentOptions }
         *     
         */
        public UpdatePgm.SET.ResidentOptions getRESIDENT() {
            return resident;
        }

        /**
         * Sets the value of the resident property.
         * 
         * @param value
         *     allowed object is
         *     {@link UpdatePgm.SET.ResidentOptions }
         *     
         */
        public void setRESIDENT(UpdatePgm.SET.ResidentOptions value) {
            this.resident = value;
        }

        /**
         * Gets the value of the schdtype property.
         * 
         * @return
         *     possible object is
         *     {@link UpdatePgm.SET.SchdtypeOptions }
         *     
         */
        public UpdatePgm.SET.SchdtypeOptions getSCHDTYPE() {
            return schdtype;
        }

        /**
         * Sets the value of the schdtype property.
         * 
         * @param value
         *     allowed object is
         *     {@link UpdatePgm.SET.SchdtypeOptions }
         *     
         */
        public void setSCHDTYPE(UpdatePgm.SET.SchdtypeOptions value) {
            this.schdtype = value;
        }

        /**
         * Gets the value of the transtat property.
         * 
         * @return
         *     possible object is
         *     {@link UpdatePgm.SET.TranstatOptions }
         *     
         */
        public UpdatePgm.SET.TranstatOptions getTRANSTAT() {
            return transtat;
        }

        /**
         * Sets the value of the transtat property.
         * 
         * @param value
         *     allowed object is
         *     {@link UpdatePgm.SET.TranstatOptions }
         *     
         */
        public void setTRANSTAT(UpdatePgm.SET.TranstatOptions value) {
            this.transtat = value;
        }


        /**
         * <p>Java class for null.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * <p>
         * <pre>
         * &lt;simpleType>
         *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
         *     &lt;enumeration value="Y"/>
         *     &lt;enumeration value="N"/>
         *   &lt;/restriction>
         * &lt;/simpleType>
         * </pre>
         * 
         */
        @XmlType(name = "")
        @XmlEnum
        public enum BmptypeOptions {

            Y,
            N;

            public String value() {
                return name();
            }

            public static UpdatePgm.SET.BmptypeOptions fromValue(String v) {
                return valueOf(v);
            }

        }


        /**
         * <p>Java class for null.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * <p>
         * <pre>
         * &lt;simpleType>
         *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
         *     &lt;enumeration value="Y"/>
         *     &lt;enumeration value="N"/>
         *   &lt;/restriction>
         * &lt;/simpleType>
         * </pre>
         * 
         */
        @XmlType(name = "")
        @XmlEnum
        public enum DoptOptions {

            Y,
            N;

            public String value() {
                return name();
            }

            public static UpdatePgm.SET.DoptOptions fromValue(String v) {
                return valueOf(v);
            }

        }


        /**
         * <p>Java class for null.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * <p>
         * <pre>
         * &lt;simpleType>
         *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
         *     &lt;enumeration value="E"/>
         *     &lt;enumeration value="N"/>
         *   &lt;/restriction>
         * &lt;/simpleType>
         * </pre>
         * 
         */
        @XmlType(name = "")
        @XmlEnum
        public enum FpOptions {

            E,
            N;

            public String value() {
                return name();
            }

            public static UpdatePgm.SET.FpOptions fromValue(String v) {
                return valueOf(v);
            }

        }


        /**
         * <p>Java class for null.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * <p>
         * <pre>
         * &lt;simpleType>
         *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
         *     &lt;enumeration value="Y"/>
         *     &lt;enumeration value="N"/>
         *   &lt;/restriction>
         * &lt;/simpleType>
         * </pre>
         * 
         */
        @XmlType(name = "")
        @XmlEnum
        public enum GpsbOptions {

            Y,
            N;

            public String value() {
                return name();
            }

            public static UpdatePgm.SET.GpsbOptions fromValue(String v) {
                return valueOf(v);
            }

        }


        /**
         * <p>Java class for null.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * <p>
         * <pre>
         * &lt;simpleType>
         *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
         *     &lt;enumeration value="ASSEM"/>
         *     &lt;enumeration value="COBOL"/>
         *     &lt;enumeration value="JAVA"/>
         *     &lt;enumeration value="PASCAL"/>
         *     &lt;enumeration value="PLI"/>
         *   &lt;/restriction>
         * &lt;/simpleType>
         * </pre>
         * 
         */
        @XmlType(name = "")
        @XmlEnum
        public enum LangOptions {

            ASSEM,
            COBOL,
            JAVA,
            PASCAL,
            PLI;

            public String value() {
                return name();
            }

            public static UpdatePgm.SET.LangOptions fromValue(String v) {
                return valueOf(v);
            }

        }


        /**
         * <p>Java class for null.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * <p>
         * <pre>
         * &lt;simpleType>
         *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
         *     &lt;enumeration value="ON"/>
         *     &lt;enumeration value="OFF"/>
         *   &lt;/restriction>
         * &lt;/simpleType>
         * </pre>
         * 
         */
        @XmlType(name = "")
        @XmlEnum
        public enum LockOptions {

            ON,
            OFF;

            public String value() {
                return name();
            }

            public static UpdatePgm.SET.LockOptions fromValue(String v) {
                return valueOf(v);
            }

        }


        /**
         * <p>Java class for null.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * <p>
         * <pre>
         * &lt;simpleType>
         *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
         *     &lt;enumeration value="N"/>
         *     &lt;enumeration value="Y"/>
         *   &lt;/restriction>
         * &lt;/simpleType>
         * </pre>
         * 
         */
        @XmlType(name = "")
        @XmlEnum
        public enum ResidentOptions {

            N,
            Y;

            public String value() {
                return name();
            }

            public static UpdatePgm.SET.ResidentOptions fromValue(String v) {
                return valueOf(v);
            }

        }


        /**
         * <p>Java class for null.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * <p>
         * <pre>
         * &lt;simpleType>
         *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
         *     &lt;enumeration value="PARALLEL"/>
         *     &lt;enumeration value="SERIAL"/>
         *   &lt;/restriction>
         * &lt;/simpleType>
         * </pre>
         * 
         */
        @XmlType(name = "")
        @XmlEnum
        public enum SchdtypeOptions {

            PARALLEL,
            SERIAL;

            public String value() {
                return name();
            }

            public static UpdatePgm.SET.SchdtypeOptions fromValue(String v) {
                return valueOf(v);
            }

        }


        /**
         * <p>Java class for null.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * <p>
         * <pre>
         * &lt;simpleType>
         *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
         *     &lt;enumeration value="N"/>
         *     &lt;enumeration value="Y"/>
         *   &lt;/restriction>
         * &lt;/simpleType>
         * </pre>
         * 
         */
        @XmlType(name = "")
        @XmlEnum
        public enum TranstatOptions {

            N,
            Y;

            public String value() {
                return name();
            }

            public static UpdatePgm.SET.TranstatOptions fromValue(String v) {
                return valueOf(v);
            }

        }

    }


    /**
     * <p>Java class for null.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * <p>
     * <pre>
     * &lt;simpleType>
     *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
     *     &lt;enumeration value="SCHD"/>
     *     &lt;enumeration value="TRACE"/>
     *     &lt;enumeration value="REFRESH"/>
     *   &lt;/restriction>
     * &lt;/simpleType>
     * </pre>
     * 
     */
    @XmlType(name = "")
    @XmlEnum
    public enum StartOptions {

        SCHD,
        TRACE,
        REFRESH;

        public String value() {
            return name();
        }

        public static UpdatePgm.StartOptions fromValue(String v) {
            return valueOf(v);
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="START" maxOccurs="unbounded" minOccurs="0">
     *           &lt;simpleType>
     *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
     *               &lt;enumeration value="SCHD"/>
     *               &lt;enumeration value="TRACE"/>
     *               &lt;enumeration value="REFRESH"/>
     *             &lt;/restriction>
     *           &lt;/simpleType>
     *         &lt;/element>
     *         &lt;element name="STOP" maxOccurs="unbounded" minOccurs="0">
     *           &lt;simpleType>
     *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
     *               &lt;enumeration value="SCHD"/>
     *               &lt;enumeration value="TRACE"/>
     *             &lt;/restriction>
     *           &lt;/simpleType>
     *         &lt;/element>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "start",
        "stop"
    })
    public static class STARTSTOP {

        @XmlElement(name = "START")
        protected List<UpdatePgm.STARTSTOP.StartOptions> start;
        @XmlElement(name = "STOP")
        protected List<UpdatePgm.STARTSTOP.StopOptions> stop;

        /**
         * Gets the value of the start property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the start property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getSTART().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link UpdatePgm.STARTSTOP.StartOptions }
         * 
         * 
         */
        public List<UpdatePgm.STARTSTOP.StartOptions> getSTART() {
            if (start == null) {
                start = new ArrayList<UpdatePgm.STARTSTOP.StartOptions>();
            }
            return this.start;
        }

        /**
         * Gets the value of the stop property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the stop property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getSTOP().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link UpdatePgm.STARTSTOP.StopOptions }
         * 
         * 
         */
        public List<UpdatePgm.STARTSTOP.StopOptions> getSTOP() {
            if (stop == null) {
                stop = new ArrayList<UpdatePgm.STARTSTOP.StopOptions>();
            }
            return this.stop;
        }


        /**
         * <p>Java class for null.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * <p>
         * <pre>
         * &lt;simpleType>
         *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
         *     &lt;enumeration value="SCHD"/>
         *     &lt;enumeration value="TRACE"/>
         *     &lt;enumeration value="REFRESH"/>
         *   &lt;/restriction>
         * &lt;/simpleType>
         * </pre>
         * 
         */
        @XmlType(name = "")
        @XmlEnum
        public enum StartOptions {

            SCHD,
            TRACE,
            REFRESH;

            public String value() {
                return name();
            }

            public static UpdatePgm.STARTSTOP.StartOptions fromValue(String v) {
                return valueOf(v);
            }

        }


        /**
         * <p>Java class for null.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * <p>
         * <pre>
         * &lt;simpleType>
         *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
         *     &lt;enumeration value="SCHD"/>
         *     &lt;enumeration value="TRACE"/>
         *   &lt;/restriction>
         * &lt;/simpleType>
         * </pre>
         * 
         */
        @XmlType(name = "")
        @XmlEnum
        public enum StopOptions {

            SCHD,
            TRACE;

            public String value() {
                return name();
            }

            public static UpdatePgm.STARTSTOP.StopOptions fromValue(String v) {
                return valueOf(v);
            }

        }

    }


    /**
     * <p>Java class for null.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * <p>
     * <pre>
     * &lt;simpleType>
     *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
     *     &lt;enumeration value="SCHD"/>
     *     &lt;enumeration value="TRACE"/>
     *   &lt;/restriction>
     * &lt;/simpleType>
     * </pre>
     * 
     */
    @XmlType(name = "")
    @XmlEnum
    public enum StopOptions {

        SCHD,
        TRACE;

        public String value() {
            return name();
        }

        public static UpdatePgm.StopOptions fromValue(String v) {
            return valueOf(v);
        }

    }

}
