/**
 *  Copyright IBM Corporation 2018, 2019
 */


// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.12.04 at 10:35:20 PM PST 
//


package commands.query.tran;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for QueryTran complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="QueryTran">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="NAME" type="{commands/query/tran}nameOptions" maxOccurs="unbounded"/>
 *         &lt;element name="CLASS" type="{http://www.w3.org/2001/XMLSchema}int" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="QCNT" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="QCNTComp">
 *                     &lt;simpleType>
 *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                         &lt;enumeration value="LT"/>
 *                         &lt;enumeration value="LE"/>
 *                         &lt;enumeration value="GT"/>
 *                         &lt;enumeration value="GE"/>
 *                         &lt;enumeration value="EQ"/>
 *                         &lt;enumeration value="NE"/>
 *                       &lt;/restriction>
 *                     &lt;/simpleType>
 *                   &lt;/element>
 *                   &lt;element name="QCNTValue" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="STATUS" maxOccurs="unbounded" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;enumeration value="AFFIN"/>
 *               &lt;enumeration value="BAL"/>
 *               &lt;enumeration value="CONV"/>
 *               &lt;enumeration value="CPIC"/>
 *               &lt;enumeration value="DYN"/>
 *               &lt;enumeration value="IOPREV"/>
 *               &lt;enumeration value="LCK"/>
 *               &lt;enumeration value="NOTINIT"/>
 *               &lt;enumeration value="QERR"/>
 *               &lt;enumeration value="QSTP"/>
 *               &lt;enumeration value="SUSPEND"/>
 *               &lt;enumeration value="STOQ"/>
 *               &lt;enumeration value="STOSCHD"/>
 *               &lt;enumeration value="TRACE"/>
 *               &lt;enumeration value="USTO"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="SHOW" maxOccurs="unbounded" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;enumeration value="AFFIN"/>
 *               &lt;enumeration value="ALL"/>
 *               &lt;enumeration value="AOCMD"/>
 *               &lt;enumeration value="CLASS"/>
 *               &lt;enumeration value="CMTMODE"/>
 *               &lt;enumeration value="CONV"/>
 *               &lt;enumeration value="CPRI"/>
 *               &lt;enumeration value="DCLWA"/>
 *               &lt;enumeration value="DEFN"/>
 *               &lt;enumeration value="DEFNTYPE"/>
 *               &lt;enumeration value="DIRROUTE"/>
 *               &lt;enumeration value="EDITRTN"/>
 *               &lt;enumeration value="EDITUC"/>
 *               &lt;enumeration value="EMHBSZ"/>
 *               &lt;enumeration value="EXPRTIME"/>
 *               &lt;enumeration value="FP"/>
 *               &lt;enumeration value="GLOBAL"/>
 *               &lt;enumeration value="IMSID"/>
 *               &lt;enumeration value="INQ"/>
 *               &lt;enumeration value="LCT"/>
 *               &lt;enumeration value="LOCAL"/>
 *               &lt;enumeration value="LPRI"/>
 *               &lt;enumeration value="MAXRGN"/>
 *               &lt;enumeration value="MODEL"/>
 *               &lt;enumeration value="MSGTYPE"/>
 *               &lt;enumeration value="MSNAME"/>
 *               &lt;enumeration value="NPRI"/>
 *               &lt;enumeration value="PARLIM"/>
 *               &lt;enumeration value="PGM"/>
 *               &lt;enumeration value="PLCT"/>
 *               &lt;enumeration value="PLCTTIME"/>
 *               &lt;enumeration value="PSB"/>
 *               &lt;enumeration value="QCNT"/>
 *               &lt;enumeration value="RECOVER"/>
 *               &lt;enumeration value="REMOTE"/>
 *               &lt;enumeration value="RESP"/>
 *               &lt;enumeration value="RGC"/>
 *               &lt;enumeration value="SEGNO"/>
 *               &lt;enumeration value="SEGSZ"/>
 *               &lt;enumeration value="SERIAL"/>
 *               &lt;enumeration value="SPASZ"/>
 *               &lt;enumeration value="SPATRUNC"/>
 *               &lt;enumeration value="STATUS"/>
 *               &lt;enumeration value="TIMESTAMP"/>
 *               &lt;enumeration value="TRANSTAT"/>
 *               &lt;enumeration value="WFI"/>
 *               &lt;enumeration value="EXPORTNEEDED"/>
 *               &lt;enumeration value="WORK"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="CONV" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;enumeration value="N"/>
 *               &lt;enumeration value="Y"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="FP" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;enumeration value="E"/>
 *               &lt;enumeration value="N"/>
 *               &lt;enumeration value="P"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="REMOTE" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;enumeration value="N"/>
 *               &lt;enumeration value="Y"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="RESP" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;enumeration value="N"/>
 *               &lt;enumeration value="Y"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "QueryTran", propOrder = {
    "name",
    "_class",
    "qcnt",
    "status",
    "show",
    "conv",
    "fp",
    "remote",
    "resp"
})
public class QueryTran {

    @XmlElement(name = "NAME", required = true)
    protected List<String> name;
    @XmlElement(name = "CLASS", type = Integer.class)
    protected List<Integer> _class;
    @XmlElement(name = "QCNT")
    protected QueryTran.QCNT qcnt;
    @XmlElement(name = "STATUS")
    protected List<QueryTran.StatusOptions> status;
    @XmlElement(name = "SHOW")
    protected List<QueryTran.ShowOptions> show;
    @XmlElement(name = "CONV")
    protected QueryTran.ConvOptions conv;
    @XmlElement(name = "FP")
    protected QueryTran.FpOptions fp;
    @XmlElement(name = "REMOTE")
    protected QueryTran.RemoteOptions remote;
    @XmlElement(name = "RESP")
    protected QueryTran.RespOptions resp;

    /**
     * Gets the value of the name property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the name property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getNAME().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     * 
     * 
     */
    public List<String> getNAME() {
        if (name == null) {
            name = new ArrayList<String>();
        }
        return this.name;
    }

    /**
     * Gets the value of the class property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the class property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getCLASS().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Integer }
     * 
     * 
     */
    public List<Integer> getCLASS() {
        if (_class == null) {
            _class = new ArrayList<Integer>();
        }
        return this._class;
    }

    /**
     * Gets the value of the qcnt property.
     * 
     * @return
     *     possible object is
     *     {@link QueryTran.QCNT }
     *     
     */
    public QueryTran.QCNT getQCNT() {
        return qcnt;
    }

    /**
     * Sets the value of the qcnt property.
     * 
     * @param value
     *     allowed object is
     *     {@link QueryTran.QCNT }
     *     
     */
    public void setQCNT(QueryTran.QCNT value) {
        this.qcnt = value;
    }

    /**
     * Gets the value of the status property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the status property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getSTATUS().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link QueryTran.StatusOptions }
     * 
     * 
     */
    public List<QueryTran.StatusOptions> getSTATUS() {
        if (status == null) {
            status = new ArrayList<QueryTran.StatusOptions>();
        }
        return this.status;
    }

    /**
     * Gets the value of the show property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the show property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getSHOW().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link QueryTran.ShowOptions }
     * 
     * 
     */
    public List<QueryTran.ShowOptions> getSHOW() {
        if (show == null) {
            show = new ArrayList<QueryTran.ShowOptions>();
        }
        return this.show;
    }

    /**
     * Gets the value of the conv property.
     * 
     * @return
     *     possible object is
     *     {@link QueryTran.ConvOptions }
     *     
     */
    public QueryTran.ConvOptions getCONV() {
        return conv;
    }

    /**
     * Sets the value of the conv property.
     * 
     * @param value
     *     allowed object is
     *     {@link QueryTran.ConvOptions }
     *     
     */
    public void setCONV(QueryTran.ConvOptions value) {
        this.conv = value;
    }

    /**
     * Gets the value of the fp property.
     * 
     * @return
     *     possible object is
     *     {@link QueryTran.FpOptions }
     *     
     */
    public QueryTran.FpOptions getFP() {
        return fp;
    }

    /**
     * Sets the value of the fp property.
     * 
     * @param value
     *     allowed object is
     *     {@link QueryTran.FpOptions }
     *     
     */
    public void setFP(QueryTran.FpOptions value) {
        this.fp = value;
    }

    /**
     * Gets the value of the remote property.
     * 
     * @return
     *     possible object is
     *     {@link QueryTran.RemoteOptions }
     *     
     */
    public QueryTran.RemoteOptions getREMOTE() {
        return remote;
    }

    /**
     * Sets the value of the remote property.
     * 
     * @param value
     *     allowed object is
     *     {@link QueryTran.RemoteOptions }
     *     
     */
    public void setREMOTE(QueryTran.RemoteOptions value) {
        this.remote = value;
    }

    /**
     * Gets the value of the resp property.
     * 
     * @return
     *     possible object is
     *     {@link QueryTran.RespOptions }
     *     
     */
    public QueryTran.RespOptions getRESP() {
        return resp;
    }

    /**
     * Sets the value of the resp property.
     * 
     * @param value
     *     allowed object is
     *     {@link QueryTran.RespOptions }
     *     
     */
    public void setRESP(QueryTran.RespOptions value) {
        this.resp = value;
    }


    /**
     * <p>Java class for null.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * <p>
     * <pre>
     * &lt;simpleType>
     *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
     *     &lt;enumeration value="N"/>
     *     &lt;enumeration value="Y"/>
     *   &lt;/restriction>
     * &lt;/simpleType>
     * </pre>
     * 
     */
    @XmlType(name = "")
    @XmlEnum
    public enum ConvOptions {

        N,
        Y;

        public String value() {
            return name();
        }

        public static QueryTran.ConvOptions fromValue(String v) {
            return valueOf(v);
        }

    }


    /**
     * <p>Java class for null.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * <p>
     * <pre>
     * &lt;simpleType>
     *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
     *     &lt;enumeration value="E"/>
     *     &lt;enumeration value="N"/>
     *     &lt;enumeration value="P"/>
     *   &lt;/restriction>
     * &lt;/simpleType>
     * </pre>
     * 
     */
    @XmlType(name = "")
    @XmlEnum
    public enum FpOptions {

        E,
        N,
        P;

        public String value() {
            return name();
        }

        public static QueryTran.FpOptions fromValue(String v) {
            return valueOf(v);
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="QCNTComp">
     *           &lt;simpleType>
     *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
     *               &lt;enumeration value="LT"/>
     *               &lt;enumeration value="LE"/>
     *               &lt;enumeration value="GT"/>
     *               &lt;enumeration value="GE"/>
     *               &lt;enumeration value="EQ"/>
     *               &lt;enumeration value="NE"/>
     *             &lt;/restriction>
     *           &lt;/simpleType>
     *         &lt;/element>
     *         &lt;element name="QCNTValue" type="{http://www.w3.org/2001/XMLSchema}int"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "qcntComp",
        "qcntValue"
    })
    public static class QCNT {

        @XmlElement(name = "QCNTComp", required = true)
        protected QueryTran.QCNT.QcntComp qcntComp;
        @XmlElement(name = "QCNTValue")
        protected int qcntValue;

        /**
         * Gets the value of the qcntComp property.
         * 
         * @return
         *     possible object is
         *     {@link QueryTran.QCNT.QcntComp }
         *     
         */
        public QueryTran.QCNT.QcntComp getQCNTComp() {
            return qcntComp;
        }

        /**
         * Sets the value of the qcntComp property.
         * 
         * @param value
         *     allowed object is
         *     {@link QueryTran.QCNT.QcntComp }
         *     
         */
        public void setQCNTComp(QueryTran.QCNT.QcntComp value) {
            this.qcntComp = value;
        }

        /**
         * Gets the value of the qcntValue property.
         * 
         */
        public int getQCNTValue() {
            return qcntValue;
        }

        /**
         * Sets the value of the qcntValue property.
         * 
         */
        public void setQCNTValue(int value) {
            this.qcntValue = value;
        }


        /**
         * <p>Java class for null.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * <p>
         * <pre>
         * &lt;simpleType>
         *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
         *     &lt;enumeration value="LT"/>
         *     &lt;enumeration value="LE"/>
         *     &lt;enumeration value="GT"/>
         *     &lt;enumeration value="GE"/>
         *     &lt;enumeration value="EQ"/>
         *     &lt;enumeration value="NE"/>
         *   &lt;/restriction>
         * &lt;/simpleType>
         * </pre>
         * 
         */
        @XmlType(name = "")
        @XmlEnum
        public enum QcntComp {

            LT,
            LE,
            GT,
            GE,
            EQ,
            NE;

            public String value() {
                return name();
            }

            public static QueryTran.QCNT.QcntComp fromValue(String v) {
                return valueOf(v);
            }

        }

    }


    /**
     * <p>Java class for null.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * <p>
     * <pre>
     * &lt;simpleType>
     *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
     *     &lt;enumeration value="N"/>
     *     &lt;enumeration value="Y"/>
     *   &lt;/restriction>
     * &lt;/simpleType>
     * </pre>
     * 
     */
    @XmlType(name = "")
    @XmlEnum
    public enum RemoteOptions {

        N,
        Y;

        public String value() {
            return name();
        }

        public static QueryTran.RemoteOptions fromValue(String v) {
            return valueOf(v);
        }

    }


    /**
     * <p>Java class for null.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * <p>
     * <pre>
     * &lt;simpleType>
     *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
     *     &lt;enumeration value="N"/>
     *     &lt;enumeration value="Y"/>
     *   &lt;/restriction>
     * &lt;/simpleType>
     * </pre>
     * 
     */
    @XmlType(name = "")
    @XmlEnum
    public enum RespOptions {

        N,
        Y;

        public String value() {
            return name();
        }

        public static QueryTran.RespOptions fromValue(String v) {
            return valueOf(v);
        }

    }


    /**
     * <p>Java class for null.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * <p>
     * <pre>
     * &lt;simpleType>
     *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
     *     &lt;enumeration value="AFFIN"/>
     *     &lt;enumeration value="ALL"/>
     *     &lt;enumeration value="AOCMD"/>
     *     &lt;enumeration value="CLASS"/>
     *     &lt;enumeration value="CMTMODE"/>
     *     &lt;enumeration value="CONV"/>
     *     &lt;enumeration value="CPRI"/>
     *     &lt;enumeration value="DCLWA"/>
     *     &lt;enumeration value="DEFN"/>
     *     &lt;enumeration value="DEFNTYPE"/>
     *     &lt;enumeration value="DIRROUTE"/>
     *     &lt;enumeration value="EDITRTN"/>
     *     &lt;enumeration value="EDITUC"/>
     *     &lt;enumeration value="EMHBSZ"/>
     *     &lt;enumeration value="EXPRTIME"/>
     *     &lt;enumeration value="FP"/>
     *     &lt;enumeration value="GLOBAL"/>
     *     &lt;enumeration value="IMSID"/>
     *     &lt;enumeration value="INQ"/>
     *     &lt;enumeration value="LCT"/>
     *     &lt;enumeration value="LOCAL"/>
     *     &lt;enumeration value="LPRI"/>
     *     &lt;enumeration value="MAXRGN"/>
     *     &lt;enumeration value="MODEL"/>
     *     &lt;enumeration value="MSGTYPE"/>
     *     &lt;enumeration value="MSNAME"/>
     *     &lt;enumeration value="NPRI"/>
     *     &lt;enumeration value="PARLIM"/>
     *     &lt;enumeration value="PGM"/>
     *     &lt;enumeration value="PLCT"/>
     *     &lt;enumeration value="PLCTTIME"/>
     *     &lt;enumeration value="PSB"/>
     *     &lt;enumeration value="QCNT"/>
     *     &lt;enumeration value="RECOVER"/>
     *     &lt;enumeration value="REMOTE"/>
     *     &lt;enumeration value="RESP"/>
     *     &lt;enumeration value="RGC"/>
     *     &lt;enumeration value="SEGNO"/>
     *     &lt;enumeration value="SEGSZ"/>
     *     &lt;enumeration value="SERIAL"/>
     *     &lt;enumeration value="SPASZ"/>
     *     &lt;enumeration value="SPATRUNC"/>
     *     &lt;enumeration value="STATUS"/>
     *     &lt;enumeration value="TIMESTAMP"/>
     *     &lt;enumeration value="TRANSTAT"/>
     *     &lt;enumeration value="WFI"/>
     *     &lt;enumeration value="EXPORTNEEDED"/>
     *     &lt;enumeration value="WORK"/>
     *   &lt;/restriction>
     * &lt;/simpleType>
     * </pre>
     * 
     */
    @XmlType(name = "")
    @XmlEnum
    public enum ShowOptions {

        AFFIN,
        ALL,
        AOCMD,
        CLASS,
        CMTMODE,
        CONV,
        CPRI,
        DCLWA,
        DEFN,
        DEFNTYPE,
        DIRROUTE,
        EDITRTN,
        EDITUC,
        EMHBSZ,
        EXPRTIME,
        FP,
        GLOBAL,
        IMSID,
        INQ,
        LCT,
        LOCAL,
        LPRI,
        MAXRGN,
        MODEL,
        MSGTYPE,
        MSNAME,
        NPRI,
        PARLIM,
        PGM,
        PLCT,
        PLCTTIME,
        PSB,
        QCNT,
        RECOVER,
        REMOTE,
        RESP,
        RGC,
        SEGNO,
        SEGSZ,
        SERIAL,
        SPASZ,
        SPATRUNC,
        STATUS,
        TIMESTAMP,
        TRANSTAT,
        WFI,
        EXPORTNEEDED,
        WORK;

        public String value() {
            return name();
        }

        public static QueryTran.ShowOptions fromValue(String v) {
            return valueOf(v);
        }

    }


    /**
     * <p>Java class for null.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * <p>
     * <pre>
     * &lt;simpleType>
     *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
     *     &lt;enumeration value="AFFIN"/>
     *     &lt;enumeration value="BAL"/>
     *     &lt;enumeration value="CONV"/>
     *     &lt;enumeration value="CPIC"/>
     *     &lt;enumeration value="DYN"/>
     *     &lt;enumeration value="IOPREV"/>
     *     &lt;enumeration value="LCK"/>
     *     &lt;enumeration value="NOTINIT"/>
     *     &lt;enumeration value="QERR"/>
     *     &lt;enumeration value="QSTP"/>
     *     &lt;enumeration value="SUSPEND"/>
     *     &lt;enumeration value="STOQ"/>
     *     &lt;enumeration value="STOSCHD"/>
     *     &lt;enumeration value="TRACE"/>
     *     &lt;enumeration value="USTO"/>
     *   &lt;/restriction>
     * &lt;/simpleType>
     * </pre>
     * 
     */
    @XmlType(name = "")
    @XmlEnum
    public enum StatusOptions {

        AFFIN,
        BAL,
        CONV,
        CPIC,
        DYN,
        IOPREV,
        LCK,
        NOTINIT,
        QERR,
        QSTP,
        SUSPEND,
        STOQ,
        STOSCHD,
        TRACE,
        USTO;

        public String value() {
            return name();
        }

        public static QueryTran.StatusOptions fromValue(String v) {
            return valueOf(v);
        }

    }

}
