/**
 *  Copyright IBM Corporation 2018, 2019
 */

//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.12.04 at 10:35:20 PM PST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "commands/query/tran", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package commands.query.tran;
