//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.11.06 at 03:48:45 PM PST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "commands/type2", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package commands.type2;
