/**
 *  Copyright IBM Corporation 2018, 2019
 */

// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.12.04 at 10:33:16 PM PST 
//


package commands.create.tran;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for CreateTran complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="CreateTran">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="NAME" type="{commands/create/tran}nameOptions" maxOccurs="unbounded"/>
 *         &lt;element name="LIKE" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;choice>
 *                   &lt;element name="DESC" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="RSC" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                 &lt;/choice>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="SET" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="AOCMD" minOccurs="0">
 *                     &lt;simpleType>
 *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                         &lt;enumeration value="CMD"/>
 *                         &lt;enumeration value="N"/>
 *                         &lt;enumeration value="TRAN"/>
 *                         &lt;enumeration value="Y"/>
 *                       &lt;/restriction>
 *                     &lt;/simpleType>
 *                   &lt;/element>
 *                   &lt;element name="CLASS" minOccurs="0">
 *                     &lt;simpleType>
 *                       &lt;restriction base="{commands/create/tran}classOptions">
 *                       &lt;/restriction>
 *                     &lt;/simpleType>
 *                   &lt;/element>
 *                   &lt;element name="CMTMODE" minOccurs="0">
 *                     &lt;simpleType>
 *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                         &lt;enumeration value="MULT"/>
 *                         &lt;enumeration value="SNGL"/>
 *                       &lt;/restriction>
 *                     &lt;/simpleType>
 *                   &lt;/element>
 *                   &lt;element name="CONV" minOccurs="0">
 *                     &lt;simpleType>
 *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                         &lt;enumeration value="N"/>
 *                         &lt;enumeration value="Y"/>
 *                       &lt;/restriction>
 *                     &lt;/simpleType>
 *                   &lt;/element>
 *                   &lt;element name="DCLWA" minOccurs="0">
 *                     &lt;simpleType>
 *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                         &lt;enumeration value="N"/>
 *                         &lt;enumeration value="Y"/>
 *                       &lt;/restriction>
 *                     &lt;/simpleType>
 *                   &lt;/element>
 *                   &lt;element name="DIRROUTE" minOccurs="0">
 *                     &lt;simpleType>
 *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                         &lt;enumeration value="N"/>
 *                         &lt;enumeration value="Y"/>
 *                       &lt;/restriction>
 *                     &lt;/simpleType>
 *                   &lt;/element>
 *                   &lt;element name="EDITRTN" minOccurs="0">
 *                     &lt;simpleType>
 *                       &lt;restriction base="{commands/create/tran}editrtnOptions">
 *                       &lt;/restriction>
 *                     &lt;/simpleType>
 *                   &lt;/element>
 *                   &lt;element name="EDITUC" minOccurs="0">
 *                     &lt;simpleType>
 *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                         &lt;enumeration value="N"/>
 *                         &lt;enumeration value="Y"/>
 *                       &lt;/restriction>
 *                     &lt;/simpleType>
 *                   &lt;/element>
 *                   &lt;element name="EMHBSZ" minOccurs="0">
 *                     &lt;simpleType>
 *                       &lt;restriction base="{commands/create/tran}emhbszOptions">
 *                       &lt;/restriction>
 *                     &lt;/simpleType>
 *                   &lt;/element>
 *                   &lt;element name="EXPRTIME" minOccurs="0">
 *                     &lt;simpleType>
 *                       &lt;restriction base="{commands/create/tran}exprtimeOptions">
 *                       &lt;/restriction>
 *                     &lt;/simpleType>
 *                   &lt;/element>
 *                   &lt;element name="FP" minOccurs="0">
 *                     &lt;simpleType>
 *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                         &lt;enumeration value="E"/>
 *                         &lt;enumeration value="N"/>
 *                         &lt;enumeration value="P"/>
 *                       &lt;/restriction>
 *                     &lt;/simpleType>
 *                   &lt;/element>
 *                   &lt;element name="INQ" minOccurs="0">
 *                     &lt;simpleType>
 *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                         &lt;enumeration value="N"/>
 *                         &lt;enumeration value="Y"/>
 *                       &lt;/restriction>
 *                     &lt;/simpleType>
 *                   &lt;/element>
 *                   &lt;element name="LCT" minOccurs="0">
 *                     &lt;simpleType>
 *                       &lt;restriction base="{commands/create/tran}lctOptions">
 *                       &lt;/restriction>
 *                     &lt;/simpleType>
 *                   &lt;/element>
 *                   &lt;element name="LPRI" minOccurs="0">
 *                     &lt;simpleType>
 *                       &lt;restriction base="{commands/create/tran}lpriOptions">
 *                       &lt;/restriction>
 *                     &lt;/simpleType>
 *                   &lt;/element>
 *                   &lt;element name="MAXRGN" minOccurs="0">
 *                     &lt;simpleType>
 *                       &lt;restriction base="{commands/create/tran}maxrgnOptions">
 *                       &lt;/restriction>
 *                     &lt;/simpleType>
 *                   &lt;/element>
 *                   &lt;element name="MSGTYPE" minOccurs="0">
 *                     &lt;simpleType>
 *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                         &lt;enumeration value="MULTSEG"/>
 *                         &lt;enumeration value="SNGLSEG"/>
 *                       &lt;/restriction>
 *                     &lt;/simpleType>
 *                   &lt;/element>
 *                   &lt;element name="MSNAME" minOccurs="0">
 *                     &lt;simpleType>
 *                       &lt;restriction base="{commands/create/tran}msnameOptions">
 *                       &lt;/restriction>
 *                     &lt;/simpleType>
 *                   &lt;/element>
 *                   &lt;element name="NPRI" minOccurs="0">
 *                     &lt;simpleType>
 *                       &lt;restriction base="{commands/create/tran}npriOptions">
 *                       &lt;/restriction>
 *                     &lt;/simpleType>
 *                   &lt;/element>
 *                   &lt;element name="PARLIM" minOccurs="0">
 *                     &lt;simpleType>
 *                       &lt;restriction base="{commands/create/tran}parlimOptions">
 *                       &lt;/restriction>
 *                     &lt;/simpleType>
 *                   &lt;/element>
 *                   &lt;element name="PGM" minOccurs="0">
 *                     &lt;simpleType>
 *                       &lt;restriction base="{commands/create/tran}pgmOptions">
 *                       &lt;/restriction>
 *                     &lt;/simpleType>
 *                   &lt;/element>
 *                   &lt;element name="PLCT" minOccurs="0">
 *                     &lt;simpleType>
 *                       &lt;restriction base="{commands/create/tran}plctOptions">
 *                       &lt;/restriction>
 *                     &lt;/simpleType>
 *                   &lt;/element>
 *                   &lt;element name="PLCTTIME" minOccurs="0">
 *                     &lt;simpleType>
 *                       &lt;restriction base="{commands/create/tran}plcttimeOptions">
 *                       &lt;/restriction>
 *                     &lt;/simpleType>
 *                   &lt;/element>
 *                   &lt;element name="RECOVER" minOccurs="0">
 *                     &lt;simpleType>
 *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                         &lt;enumeration value="N"/>
 *                         &lt;enumeration value="Y"/>
 *                       &lt;/restriction>
 *                     &lt;/simpleType>
 *                   &lt;/element>
 *                   &lt;element name="REMOTE" minOccurs="0">
 *                     &lt;simpleType>
 *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                         &lt;enumeration value="N"/>
 *                         &lt;enumeration value="Y"/>
 *                       &lt;/restriction>
 *                     &lt;/simpleType>
 *                   &lt;/element>
 *                   &lt;element name="RESP" minOccurs="0">
 *                     &lt;simpleType>
 *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                         &lt;enumeration value="N"/>
 *                         &lt;enumeration value="Y"/>
 *                       &lt;/restriction>
 *                     &lt;/simpleType>
 *                   &lt;/element>
 *                   &lt;element name="SEGNO" minOccurs="0">
 *                     &lt;simpleType>
 *                       &lt;restriction base="{commands/create/tran}segnoOptions">
 *                       &lt;/restriction>
 *                     &lt;/simpleType>
 *                   &lt;/element>
 *                   &lt;element name="SEGSZ" minOccurs="0">
 *                     &lt;simpleType>
 *                       &lt;restriction base="{commands/create/tran}segszOptions">
 *                       &lt;/restriction>
 *                     &lt;/simpleType>
 *                   &lt;/element>
 *                   &lt;element name="SERIAL" minOccurs="0">
 *                     &lt;simpleType>
 *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                         &lt;enumeration value="N"/>
 *                         &lt;enumeration value="Y"/>
 *                       &lt;/restriction>
 *                     &lt;/simpleType>
 *                   &lt;/element>
 *                   &lt;element name="SIDL" minOccurs="0">
 *                     &lt;simpleType>
 *                       &lt;restriction base="{commands/create/tran}sidlOptions">
 *                       &lt;/restriction>
 *                     &lt;/simpleType>
 *                   &lt;/element>
 *                   &lt;element name="SIDR" minOccurs="0">
 *                     &lt;simpleType>
 *                       &lt;restriction base="{commands/create/tran}sidrOptions">
 *                       &lt;/restriction>
 *                     &lt;/simpleType>
 *                   &lt;/element>
 *                   &lt;element name="SPASZ" minOccurs="0">
 *                     &lt;simpleType>
 *                       &lt;restriction base="{commands/create/tran}spaszOptions">
 *                       &lt;/restriction>
 *                     &lt;/simpleType>
 *                   &lt;/element>
 *                   &lt;element name="SPATRUNC" minOccurs="0">
 *                     &lt;simpleType>
 *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                         &lt;enumeration value="R"/>
 *                         &lt;enumeration value="S"/>
 *                       &lt;/restriction>
 *                     &lt;/simpleType>
 *                   &lt;/element>
 *                   &lt;element name="TRANSTAT" minOccurs="0">
 *                     &lt;simpleType>
 *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                         &lt;enumeration value="N"/>
 *                         &lt;enumeration value="Y"/>
 *                       &lt;/restriction>
 *                     &lt;/simpleType>
 *                   &lt;/element>
 *                   &lt;element name="WFI" minOccurs="0">
 *                     &lt;simpleType>
 *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                         &lt;enumeration value="N"/>
 *                         &lt;enumeration value="Y"/>
 *                       &lt;/restriction>
 *                     &lt;/simpleType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "CreateTran", propOrder = {
    "name",
    "like",
    "set"
})
public class CreateTran {

    @XmlElement(name = "NAME", required = true)
    protected List<String> name;
    @XmlElement(name = "LIKE")
    protected CreateTran.LIKE like;
    @XmlElement(name = "SET")
    protected CreateTran.SET set;

    /**
     * Gets the value of the name property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the name property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getNAME().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     * 
     * 
     */
    public List<String> getNAME() {
        if (name == null) {
            name = new ArrayList<String>();
        }
        return this.name;
    }

    /**
     * Gets the value of the like property.
     * 
     * @return
     *     possible object is
     *     {@link CreateTran.LIKE }
     *     
     */
    public CreateTran.LIKE getLIKE() {
        return like;
    }

    /**
     * Sets the value of the like property.
     * 
     * @param value
     *     allowed object is
     *     {@link CreateTran.LIKE }
     *     
     */
    public void setLIKE(CreateTran.LIKE value) {
        this.like = value;
    }

    /**
     * Gets the value of the set property.
     * 
     * @return
     *     possible object is
     *     {@link CreateTran.SET }
     *     
     */
    public CreateTran.SET getSET() {
        return set;
    }

    /**
     * Sets the value of the set property.
     * 
     * @param value
     *     allowed object is
     *     {@link CreateTran.SET }
     *     
     */
    public void setSET(CreateTran.SET value) {
        this.set = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;choice>
     *         &lt;element name="DESC" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="RSC" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *       &lt;/choice>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "desc",
        "rsc"
    })
    public static class LIKE {

        @XmlElement(name = "DESC")
        protected String desc;
        @XmlElement(name = "RSC")
        protected String rsc;

        /**
         * Gets the value of the desc property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getDESC() {
            return desc;
        }

        /**
         * Sets the value of the desc property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setDESC(String value) {
            this.desc = value;
        }

        /**
         * Gets the value of the rsc property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getRSC() {
            return rsc;
        }

        /**
         * Sets the value of the rsc property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setRSC(String value) {
            this.rsc = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="AOCMD" minOccurs="0">
     *           &lt;simpleType>
     *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
     *               &lt;enumeration value="CMD"/>
     *               &lt;enumeration value="N"/>
     *               &lt;enumeration value="TRAN"/>
     *               &lt;enumeration value="Y"/>
     *             &lt;/restriction>
     *           &lt;/simpleType>
     *         &lt;/element>
     *         &lt;element name="CLASS" minOccurs="0">
     *           &lt;simpleType>
     *             &lt;restriction base="{commands/create/tran}classOptions">
     *             &lt;/restriction>
     *           &lt;/simpleType>
     *         &lt;/element>
     *         &lt;element name="CMTMODE" minOccurs="0">
     *           &lt;simpleType>
     *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
     *               &lt;enumeration value="MULT"/>
     *               &lt;enumeration value="SNGL"/>
     *             &lt;/restriction>
     *           &lt;/simpleType>
     *         &lt;/element>
     *         &lt;element name="CONV" minOccurs="0">
     *           &lt;simpleType>
     *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
     *               &lt;enumeration value="N"/>
     *               &lt;enumeration value="Y"/>
     *             &lt;/restriction>
     *           &lt;/simpleType>
     *         &lt;/element>
     *         &lt;element name="DCLWA" minOccurs="0">
     *           &lt;simpleType>
     *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
     *               &lt;enumeration value="N"/>
     *               &lt;enumeration value="Y"/>
     *             &lt;/restriction>
     *           &lt;/simpleType>
     *         &lt;/element>
     *         &lt;element name="DIRROUTE" minOccurs="0">
     *           &lt;simpleType>
     *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
     *               &lt;enumeration value="N"/>
     *               &lt;enumeration value="Y"/>
     *             &lt;/restriction>
     *           &lt;/simpleType>
     *         &lt;/element>
     *         &lt;element name="EDITRTN" minOccurs="0">
     *           &lt;simpleType>
     *             &lt;restriction base="{commands/create/tran}editrtnOptions">
     *             &lt;/restriction>
     *           &lt;/simpleType>
     *         &lt;/element>
     *         &lt;element name="EDITUC" minOccurs="0">
     *           &lt;simpleType>
     *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
     *               &lt;enumeration value="N"/>
     *               &lt;enumeration value="Y"/>
     *             &lt;/restriction>
     *           &lt;/simpleType>
     *         &lt;/element>
     *         &lt;element name="EMHBSZ" minOccurs="0">
     *           &lt;simpleType>
     *             &lt;restriction base="{commands/create/tran}emhbszOptions">
     *             &lt;/restriction>
     *           &lt;/simpleType>
     *         &lt;/element>
     *         &lt;element name="EXPRTIME" minOccurs="0">
     *           &lt;simpleType>
     *             &lt;restriction base="{commands/create/tran}exprtimeOptions">
     *             &lt;/restriction>
     *           &lt;/simpleType>
     *         &lt;/element>
     *         &lt;element name="FP" minOccurs="0">
     *           &lt;simpleType>
     *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
     *               &lt;enumeration value="E"/>
     *               &lt;enumeration value="N"/>
     *               &lt;enumeration value="P"/>
     *             &lt;/restriction>
     *           &lt;/simpleType>
     *         &lt;/element>
     *         &lt;element name="INQ" minOccurs="0">
     *           &lt;simpleType>
     *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
     *               &lt;enumeration value="N"/>
     *               &lt;enumeration value="Y"/>
     *             &lt;/restriction>
     *           &lt;/simpleType>
     *         &lt;/element>
     *         &lt;element name="LCT" minOccurs="0">
     *           &lt;simpleType>
     *             &lt;restriction base="{commands/create/tran}lctOptions">
     *             &lt;/restriction>
     *           &lt;/simpleType>
     *         &lt;/element>
     *         &lt;element name="LPRI" minOccurs="0">
     *           &lt;simpleType>
     *             &lt;restriction base="{commands/create/tran}lpriOptions">
     *             &lt;/restriction>
     *           &lt;/simpleType>
     *         &lt;/element>
     *         &lt;element name="MAXRGN" minOccurs="0">
     *           &lt;simpleType>
     *             &lt;restriction base="{commands/create/tran}maxrgnOptions">
     *             &lt;/restriction>
     *           &lt;/simpleType>
     *         &lt;/element>
     *         &lt;element name="MSGTYPE" minOccurs="0">
     *           &lt;simpleType>
     *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
     *               &lt;enumeration value="MULTSEG"/>
     *               &lt;enumeration value="SNGLSEG"/>
     *             &lt;/restriction>
     *           &lt;/simpleType>
     *         &lt;/element>
     *         &lt;element name="MSNAME" minOccurs="0">
     *           &lt;simpleType>
     *             &lt;restriction base="{commands/create/tran}msnameOptions">
     *             &lt;/restriction>
     *           &lt;/simpleType>
     *         &lt;/element>
     *         &lt;element name="NPRI" minOccurs="0">
     *           &lt;simpleType>
     *             &lt;restriction base="{commands/create/tran}npriOptions">
     *             &lt;/restriction>
     *           &lt;/simpleType>
     *         &lt;/element>
     *         &lt;element name="PARLIM" minOccurs="0">
     *           &lt;simpleType>
     *             &lt;restriction base="{commands/create/tran}parlimOptions">
     *             &lt;/restriction>
     *           &lt;/simpleType>
     *         &lt;/element>
     *         &lt;element name="PGM" minOccurs="0">
     *           &lt;simpleType>
     *             &lt;restriction base="{commands/create/tran}pgmOptions">
     *             &lt;/restriction>
     *           &lt;/simpleType>
     *         &lt;/element>
     *         &lt;element name="PLCT" minOccurs="0">
     *           &lt;simpleType>
     *             &lt;restriction base="{commands/create/tran}plctOptions">
     *             &lt;/restriction>
     *           &lt;/simpleType>
     *         &lt;/element>
     *         &lt;element name="PLCTTIME" minOccurs="0">
     *           &lt;simpleType>
     *             &lt;restriction base="{commands/create/tran}plcttimeOptions">
     *             &lt;/restriction>
     *           &lt;/simpleType>
     *         &lt;/element>
     *         &lt;element name="RECOVER" minOccurs="0">
     *           &lt;simpleType>
     *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
     *               &lt;enumeration value="N"/>
     *               &lt;enumeration value="Y"/>
     *             &lt;/restriction>
     *           &lt;/simpleType>
     *         &lt;/element>
     *         &lt;element name="REMOTE" minOccurs="0">
     *           &lt;simpleType>
     *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
     *               &lt;enumeration value="N"/>
     *               &lt;enumeration value="Y"/>
     *             &lt;/restriction>
     *           &lt;/simpleType>
     *         &lt;/element>
     *         &lt;element name="RESP" minOccurs="0">
     *           &lt;simpleType>
     *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
     *               &lt;enumeration value="N"/>
     *               &lt;enumeration value="Y"/>
     *             &lt;/restriction>
     *           &lt;/simpleType>
     *         &lt;/element>
     *         &lt;element name="SEGNO" minOccurs="0">
     *           &lt;simpleType>
     *             &lt;restriction base="{commands/create/tran}segnoOptions">
     *             &lt;/restriction>
     *           &lt;/simpleType>
     *         &lt;/element>
     *         &lt;element name="SEGSZ" minOccurs="0">
     *           &lt;simpleType>
     *             &lt;restriction base="{commands/create/tran}segszOptions">
     *             &lt;/restriction>
     *           &lt;/simpleType>
     *         &lt;/element>
     *         &lt;element name="SERIAL" minOccurs="0">
     *           &lt;simpleType>
     *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
     *               &lt;enumeration value="N"/>
     *               &lt;enumeration value="Y"/>
     *             &lt;/restriction>
     *           &lt;/simpleType>
     *         &lt;/element>
     *         &lt;element name="SIDL" minOccurs="0">
     *           &lt;simpleType>
     *             &lt;restriction base="{commands/create/tran}sidlOptions">
     *             &lt;/restriction>
     *           &lt;/simpleType>
     *         &lt;/element>
     *         &lt;element name="SIDR" minOccurs="0">
     *           &lt;simpleType>
     *             &lt;restriction base="{commands/create/tran}sidrOptions">
     *             &lt;/restriction>
     *           &lt;/simpleType>
     *         &lt;/element>
     *         &lt;element name="SPASZ" minOccurs="0">
     *           &lt;simpleType>
     *             &lt;restriction base="{commands/create/tran}spaszOptions">
     *             &lt;/restriction>
     *           &lt;/simpleType>
     *         &lt;/element>
     *         &lt;element name="SPATRUNC" minOccurs="0">
     *           &lt;simpleType>
     *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
     *               &lt;enumeration value="R"/>
     *               &lt;enumeration value="S"/>
     *             &lt;/restriction>
     *           &lt;/simpleType>
     *         &lt;/element>
     *         &lt;element name="TRANSTAT" minOccurs="0">
     *           &lt;simpleType>
     *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
     *               &lt;enumeration value="N"/>
     *               &lt;enumeration value="Y"/>
     *             &lt;/restriction>
     *           &lt;/simpleType>
     *         &lt;/element>
     *         &lt;element name="WFI" minOccurs="0">
     *           &lt;simpleType>
     *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
     *               &lt;enumeration value="N"/>
     *               &lt;enumeration value="Y"/>
     *             &lt;/restriction>
     *           &lt;/simpleType>
     *         &lt;/element>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "aocmd",
        "_class",
        "cmtmode",
        "conv",
        "dclwa",
        "dirroute",
        "editrtn",
        "edituc",
        "emhbsz",
        "exprtime",
        "fp",
        "inq",
        "lct",
        "lpri",
        "maxrgn",
        "msgtype",
        "msname",
        "npri",
        "parlim",
        "pgm",
        "plct",
        "plcttime",
        "recover",
        "remote",
        "resp",
        "segno",
        "segsz",
        "serial",
        "sidl",
        "sidr",
        "spasz",
        "spatrunc",
        "transtat",
        "wfi"
    })
    public static class SET {

        @XmlElement(name = "AOCMD")
        protected CreateTran.SET.AocmdOptions aocmd;
        @XmlElement(name = "CLASS")
        protected Integer _class;
        @XmlElement(name = "CMTMODE")
        protected CreateTran.SET.CmtmodeOptions cmtmode;
        @XmlElement(name = "CONV")
        protected CreateTran.SET.ConvOptions conv;
        @XmlElement(name = "DCLWA")
        protected CreateTran.SET.DclwaOptions dclwa;
        @XmlElement(name = "DIRROUTE")
        protected CreateTran.SET.DirrouteOptions dirroute;
        @XmlElement(name = "EDITRTN")
        protected String editrtn;
        @XmlElement(name = "EDITUC")
        protected CreateTran.SET.EditucOptions edituc;
        @XmlElement(name = "EMHBSZ")
        protected Integer emhbsz;
        @XmlElement(name = "EXPRTIME")
        protected Integer exprtime;
        @XmlElement(name = "FP")
        protected CreateTran.SET.FpOptions fp;
        @XmlElement(name = "INQ")
        protected CreateTran.SET.InqOptions inq;
        @XmlElement(name = "LCT")
        protected Integer lct;
        @XmlElement(name = "LPRI")
        protected Integer lpri;
        @XmlElement(name = "MAXRGN")
        protected Integer maxrgn;
        @XmlElement(name = "MSGTYPE")
        protected CreateTran.SET.MsgtypeOptions msgtype;
        @XmlElement(name = "MSNAME")
        protected String msname;
        @XmlElement(name = "NPRI")
        protected Integer npri;
        @XmlElement(name = "PARLIM")
        protected Integer parlim;
        @XmlElement(name = "PGM")
        protected String pgm;
        @XmlElement(name = "PLCT")
        protected Integer plct;
        @XmlElement(name = "PLCTTIME")
        protected Integer plcttime;
        @XmlElement(name = "RECOVER")
        protected CreateTran.SET.RecoverOptions recover;
        @XmlElement(name = "REMOTE")
        protected CreateTran.SET.RemoteOptions remote;
        @XmlElement(name = "RESP")
        protected CreateTran.SET.RespOptions resp;
        @XmlElement(name = "SEGNO")
        protected Integer segno;
        @XmlElement(name = "SEGSZ")
        protected Integer segsz;
        @XmlElement(name = "SERIAL")
        protected CreateTran.SET.SerialOptions serial;
        @XmlElement(name = "SIDL")
        protected Integer sidl;
        @XmlElement(name = "SIDR")
        protected Integer sidr;
        @XmlElement(name = "SPASZ")
        protected Integer spasz;
        @XmlElement(name = "SPATRUNC")
        protected CreateTran.SET.SpatruncOptions spatrunc;
        @XmlElement(name = "TRANSTAT")
        protected CreateTran.SET.TranstatOptions transtat;
        @XmlElement(name = "WFI")
        protected CreateTran.SET.WfiOptions wfi;

        /**
         * Gets the value of the aocmd property.
         * 
         * @return
         *     possible object is
         *     {@link CreateTran.SET.AocmdOptions }
         *     
         */
        public CreateTran.SET.AocmdOptions getAOCMD() {
            return aocmd;
        }

        /**
         * Sets the value of the aocmd property.
         * 
         * @param value
         *     allowed object is
         *     {@link CreateTran.SET.AocmdOptions }
         *     
         */
        public void setAOCMD(CreateTran.SET.AocmdOptions value) {
            this.aocmd = value;
        }

        /**
         * Gets the value of the class property.
         * 
         * @return
         *     possible object is
         *     {@link Integer }
         *     
         */
        public Integer getCLASS() {
            return _class;
        }

        /**
         * Sets the value of the class property.
         * 
         * @param value
         *     allowed object is
         *     {@link Integer }
         *     
         */
        public void setCLASS(Integer value) {
            this._class = value;
        }

        /**
         * Gets the value of the cmtmode property.
         * 
         * @return
         *     possible object is
         *     {@link CreateTran.SET.CmtmodeOptions }
         *     
         */
        public CreateTran.SET.CmtmodeOptions getCMTMODE() {
            return cmtmode;
        }

        /**
         * Sets the value of the cmtmode property.
         * 
         * @param value
         *     allowed object is
         *     {@link CreateTran.SET.CmtmodeOptions }
         *     
         */
        public void setCMTMODE(CreateTran.SET.CmtmodeOptions value) {
            this.cmtmode = value;
        }

        /**
         * Gets the value of the conv property.
         * 
         * @return
         *     possible object is
         *     {@link CreateTran.SET.ConvOptions }
         *     
         */
        public CreateTran.SET.ConvOptions getCONV() {
            return conv;
        }

        /**
         * Sets the value of the conv property.
         * 
         * @param value
         *     allowed object is
         *     {@link CreateTran.SET.ConvOptions }
         *     
         */
        public void setCONV(CreateTran.SET.ConvOptions value) {
            this.conv = value;
        }

        /**
         * Gets the value of the dclwa property.
         * 
         * @return
         *     possible object is
         *     {@link CreateTran.SET.DclwaOptions }
         *     
         */
        public CreateTran.SET.DclwaOptions getDCLWA() {
            return dclwa;
        }

        /**
         * Sets the value of the dclwa property.
         * 
         * @param value
         *     allowed object is
         *     {@link CreateTran.SET.DclwaOptions }
         *     
         */
        public void setDCLWA(CreateTran.SET.DclwaOptions value) {
            this.dclwa = value;
        }

        /**
         * Gets the value of the dirroute property.
         * 
         * @return
         *     possible object is
         *     {@link CreateTran.SET.DirrouteOptions }
         *     
         */
        public CreateTran.SET.DirrouteOptions getDIRROUTE() {
            return dirroute;
        }

        /**
         * Sets the value of the dirroute property.
         * 
         * @param value
         *     allowed object is
         *     {@link CreateTran.SET.DirrouteOptions }
         *     
         */
        public void setDIRROUTE(CreateTran.SET.DirrouteOptions value) {
            this.dirroute = value;
        }

        /**
         * Gets the value of the editrtn property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getEDITRTN() {
            return editrtn;
        }

        /**
         * Sets the value of the editrtn property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setEDITRTN(String value) {
            this.editrtn = value;
        }

        /**
         * Gets the value of the edituc property.
         * 
         * @return
         *     possible object is
         *     {@link CreateTran.SET.EditucOptions }
         *     
         */
        public CreateTran.SET.EditucOptions getEDITUC() {
            return edituc;
        }

        /**
         * Sets the value of the edituc property.
         * 
         * @param value
         *     allowed object is
         *     {@link CreateTran.SET.EditucOptions }
         *     
         */
        public void setEDITUC(CreateTran.SET.EditucOptions value) {
            this.edituc = value;
        }

        /**
         * Gets the value of the emhbsz property.
         * 
         * @return
         *     possible object is
         *     {@link Integer }
         *     
         */
        public Integer getEMHBSZ() {
            return emhbsz;
        }

        /**
         * Sets the value of the emhbsz property.
         * 
         * @param value
         *     allowed object is
         *     {@link Integer }
         *     
         */
        public void setEMHBSZ(Integer value) {
            this.emhbsz = value;
        }

        /**
         * Gets the value of the exprtime property.
         * 
         * @return
         *     possible object is
         *     {@link Integer }
         *     
         */
        public Integer getEXPRTIME() {
            return exprtime;
        }

        /**
         * Sets the value of the exprtime property.
         * 
         * @param value
         *     allowed object is
         *     {@link Integer }
         *     
         */
        public void setEXPRTIME(Integer value) {
            this.exprtime = value;
        }

        /**
         * Gets the value of the fp property.
         * 
         * @return
         *     possible object is
         *     {@link CreateTran.SET.FpOptions }
         *     
         */
        public CreateTran.SET.FpOptions getFP() {
            return fp;
        }

        /**
         * Sets the value of the fp property.
         * 
         * @param value
         *     allowed object is
         *     {@link CreateTran.SET.FpOptions }
         *     
         */
        public void setFP(CreateTran.SET.FpOptions value) {
            this.fp = value;
        }

        /**
         * Gets the value of the inq property.
         * 
         * @return
         *     possible object is
         *     {@link CreateTran.SET.InqOptions }
         *     
         */
        public CreateTran.SET.InqOptions getINQ() {
            return inq;
        }

        /**
         * Sets the value of the inq property.
         * 
         * @param value
         *     allowed object is
         *     {@link CreateTran.SET.InqOptions }
         *     
         */
        public void setINQ(CreateTran.SET.InqOptions value) {
            this.inq = value;
        }

        /**
         * Gets the value of the lct property.
         * 
         * @return
         *     possible object is
         *     {@link Integer }
         *     
         */
        public Integer getLCT() {
            return lct;
        }

        /**
         * Sets the value of the lct property.
         * 
         * @param value
         *     allowed object is
         *     {@link Integer }
         *     
         */
        public void setLCT(Integer value) {
            this.lct = value;
        }

        /**
         * Gets the value of the lpri property.
         * 
         * @return
         *     possible object is
         *     {@link Integer }
         *     
         */
        public Integer getLPRI() {
            return lpri;
        }

        /**
         * Sets the value of the lpri property.
         * 
         * @param value
         *     allowed object is
         *     {@link Integer }
         *     
         */
        public void setLPRI(Integer value) {
            this.lpri = value;
        }

        /**
         * Gets the value of the maxrgn property.
         * 
         * @return
         *     possible object is
         *     {@link Integer }
         *     
         */
        public Integer getMAXRGN() {
            return maxrgn;
        }

        /**
         * Sets the value of the maxrgn property.
         * 
         * @param value
         *     allowed object is
         *     {@link Integer }
         *     
         */
        public void setMAXRGN(Integer value) {
            this.maxrgn = value;
        }

        /**
         * Gets the value of the msgtype property.
         * 
         * @return
         *     possible object is
         *     {@link CreateTran.SET.MsgtypeOptions }
         *     
         */
        public CreateTran.SET.MsgtypeOptions getMSGTYPE() {
            return msgtype;
        }

        /**
         * Sets the value of the msgtype property.
         * 
         * @param value
         *     allowed object is
         *     {@link CreateTran.SET.MsgtypeOptions }
         *     
         */
        public void setMSGTYPE(CreateTran.SET.MsgtypeOptions value) {
            this.msgtype = value;
        }

        /**
         * Gets the value of the msname property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getMSNAME() {
            return msname;
        }

        /**
         * Sets the value of the msname property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setMSNAME(String value) {
            this.msname = value;
        }

        /**
         * Gets the value of the npri property.
         * 
         * @return
         *     possible object is
         *     {@link Integer }
         *     
         */
        public Integer getNPRI() {
            return npri;
        }

        /**
         * Sets the value of the npri property.
         * 
         * @param value
         *     allowed object is
         *     {@link Integer }
         *     
         */
        public void setNPRI(Integer value) {
            this.npri = value;
        }

        /**
         * Gets the value of the parlim property.
         * 
         * @return
         *     possible object is
         *     {@link Integer }
         *     
         */
        public Integer getPARLIM() {
            return parlim;
        }

        /**
         * Sets the value of the parlim property.
         * 
         * @param value
         *     allowed object is
         *     {@link Integer }
         *     
         */
        public void setPARLIM(Integer value) {
            this.parlim = value;
        }

        /**
         * Gets the value of the pgm property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getPGM() {
            return pgm;
        }

        /**
         * Sets the value of the pgm property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setPGM(String value) {
            this.pgm = value;
        }

        /**
         * Gets the value of the plct property.
         * 
         * @return
         *     possible object is
         *     {@link Integer }
         *     
         */
        public Integer getPLCT() {
            return plct;
        }

        /**
         * Sets the value of the plct property.
         * 
         * @param value
         *     allowed object is
         *     {@link Integer }
         *     
         */
        public void setPLCT(Integer value) {
            this.plct = value;
        }

        /**
         * Gets the value of the plcttime property.
         * 
         * @return
         *     possible object is
         *     {@link Integer }
         *     
         */
        public Integer getPLCTTIME() {
            return plcttime;
        }

        /**
         * Sets the value of the plcttime property.
         * 
         * @param value
         *     allowed object is
         *     {@link Integer }
         *     
         */
        public void setPLCTTIME(Integer value) {
            this.plcttime = value;
        }

        /**
         * Gets the value of the recover property.
         * 
         * @return
         *     possible object is
         *     {@link CreateTran.SET.RecoverOptions }
         *     
         */
        public CreateTran.SET.RecoverOptions getRECOVER() {
            return recover;
        }

        /**
         * Sets the value of the recover property.
         * 
         * @param value
         *     allowed object is
         *     {@link CreateTran.SET.RecoverOptions }
         *     
         */
        public void setRECOVER(CreateTran.SET.RecoverOptions value) {
            this.recover = value;
        }

        /**
         * Gets the value of the remote property.
         * 
         * @return
         *     possible object is
         *     {@link CreateTran.SET.RemoteOptions }
         *     
         */
        public CreateTran.SET.RemoteOptions getREMOTE() {
            return remote;
        }

        /**
         * Sets the value of the remote property.
         * 
         * @param value
         *     allowed object is
         *     {@link CreateTran.SET.RemoteOptions }
         *     
         */
        public void setREMOTE(CreateTran.SET.RemoteOptions value) {
            this.remote = value;
        }

        /**
         * Gets the value of the resp property.
         * 
         * @return
         *     possible object is
         *     {@link CreateTran.SET.RespOptions }
         *     
         */
        public CreateTran.SET.RespOptions getRESP() {
            return resp;
        }

        /**
         * Sets the value of the resp property.
         * 
         * @param value
         *     allowed object is
         *     {@link CreateTran.SET.RespOptions }
         *     
         */
        public void setRESP(CreateTran.SET.RespOptions value) {
            this.resp = value;
        }

        /**
         * Gets the value of the segno property.
         * 
         * @return
         *     possible object is
         *     {@link Integer }
         *     
         */
        public Integer getSEGNO() {
            return segno;
        }

        /**
         * Sets the value of the segno property.
         * 
         * @param value
         *     allowed object is
         *     {@link Integer }
         *     
         */
        public void setSEGNO(Integer value) {
            this.segno = value;
        }

        /**
         * Gets the value of the segsz property.
         * 
         * @return
         *     possible object is
         *     {@link Integer }
         *     
         */
        public Integer getSEGSZ() {
            return segsz;
        }

        /**
         * Sets the value of the segsz property.
         * 
         * @param value
         *     allowed object is
         *     {@link Integer }
         *     
         */
        public void setSEGSZ(Integer value) {
            this.segsz = value;
        }

        /**
         * Gets the value of the serial property.
         * 
         * @return
         *     possible object is
         *     {@link CreateTran.SET.SerialOptions }
         *     
         */
        public CreateTran.SET.SerialOptions getSERIAL() {
            return serial;
        }

        /**
         * Sets the value of the serial property.
         * 
         * @param value
         *     allowed object is
         *     {@link CreateTran.SET.SerialOptions }
         *     
         */
        public void setSERIAL(CreateTran.SET.SerialOptions value) {
            this.serial = value;
        }

        /**
         * Gets the value of the sidl property.
         * 
         * @return
         *     possible object is
         *     {@link Integer }
         *     
         */
        public Integer getSIDL() {
            return sidl;
        }

        /**
         * Sets the value of the sidl property.
         * 
         * @param value
         *     allowed object is
         *     {@link Integer }
         *     
         */
        public void setSIDL(Integer value) {
            this.sidl = value;
        }

        /**
         * Gets the value of the sidr property.
         * 
         * @return
         *     possible object is
         *     {@link Integer }
         *     
         */
        public Integer getSIDR() {
            return sidr;
        }

        /**
         * Sets the value of the sidr property.
         * 
         * @param value
         *     allowed object is
         *     {@link Integer }
         *     
         */
        public void setSIDR(Integer value) {
            this.sidr = value;
        }

        /**
         * Gets the value of the spasz property.
         * 
         * @return
         *     possible object is
         *     {@link Integer }
         *     
         */
        public Integer getSPASZ() {
            return spasz;
        }

        /**
         * Sets the value of the spasz property.
         * 
         * @param value
         *     allowed object is
         *     {@link Integer }
         *     
         */
        public void setSPASZ(Integer value) {
            this.spasz = value;
        }

        /**
         * Gets the value of the spatrunc property.
         * 
         * @return
         *     possible object is
         *     {@link CreateTran.SET.SpatruncOptions }
         *     
         */
        public CreateTran.SET.SpatruncOptions getSPATRUNC() {
            return spatrunc;
        }

        /**
         * Sets the value of the spatrunc property.
         * 
         * @param value
         *     allowed object is
         *     {@link CreateTran.SET.SpatruncOptions }
         *     
         */
        public void setSPATRUNC(CreateTran.SET.SpatruncOptions value) {
            this.spatrunc = value;
        }

        /**
         * Gets the value of the transtat property.
         * 
         * @return
         *     possible object is
         *     {@link CreateTran.SET.TranstatOptions }
         *     
         */
        public CreateTran.SET.TranstatOptions getTRANSTAT() {
            return transtat;
        }

        /**
         * Sets the value of the transtat property.
         * 
         * @param value
         *     allowed object is
         *     {@link CreateTran.SET.TranstatOptions }
         *     
         */
        public void setTRANSTAT(CreateTran.SET.TranstatOptions value) {
            this.transtat = value;
        }

        /**
         * Gets the value of the wfi property.
         * 
         * @return
         *     possible object is
         *     {@link CreateTran.SET.WfiOptions }
         *     
         */
        public CreateTran.SET.WfiOptions getWFI() {
            return wfi;
        }

        /**
         * Sets the value of the wfi property.
         * 
         * @param value
         *     allowed object is
         *     {@link CreateTran.SET.WfiOptions }
         *     
         */
        public void setWFI(CreateTran.SET.WfiOptions value) {
            this.wfi = value;
        }


        /**
         * <p>Java class for null.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * <p>
         * <pre>
         * &lt;simpleType>
         *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
         *     &lt;enumeration value="CMD"/>
         *     &lt;enumeration value="N"/>
         *     &lt;enumeration value="TRAN"/>
         *     &lt;enumeration value="Y"/>
         *   &lt;/restriction>
         * &lt;/simpleType>
         * </pre>
         * 
         */
        @XmlType(name = "")
        @XmlEnum
        public enum AocmdOptions {

            CMD,
            N,
            TRAN,
            Y;

            public String value() {
                return name();
            }

            public static CreateTran.SET.AocmdOptions fromValue(String v) {
                return valueOf(v);
            }

        }


        /**
         * <p>Java class for null.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * <p>
         * <pre>
         * &lt;simpleType>
         *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
         *     &lt;enumeration value="MULT"/>
         *     &lt;enumeration value="SNGL"/>
         *   &lt;/restriction>
         * &lt;/simpleType>
         * </pre>
         * 
         */
        @XmlType(name = "")
        @XmlEnum
        public enum CmtmodeOptions {

            MULT,
            SNGL;

            public String value() {
                return name();
            }

            public static CreateTran.SET.CmtmodeOptions fromValue(String v) {
                return valueOf(v);
            }

        }


        /**
         * <p>Java class for null.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * <p>
         * <pre>
         * &lt;simpleType>
         *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
         *     &lt;enumeration value="N"/>
         *     &lt;enumeration value="Y"/>
         *   &lt;/restriction>
         * &lt;/simpleType>
         * </pre>
         * 
         */
        @XmlType(name = "")
        @XmlEnum
        public enum ConvOptions {

            N,
            Y;

            public String value() {
                return name();
            }

            public static CreateTran.SET.ConvOptions fromValue(String v) {
                return valueOf(v);
            }

        }


        /**
         * <p>Java class for null.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * <p>
         * <pre>
         * &lt;simpleType>
         *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
         *     &lt;enumeration value="N"/>
         *     &lt;enumeration value="Y"/>
         *   &lt;/restriction>
         * &lt;/simpleType>
         * </pre>
         * 
         */
        @XmlType(name = "")
        @XmlEnum
        public enum DclwaOptions {

            N,
            Y;

            public String value() {
                return name();
            }

            public static CreateTran.SET.DclwaOptions fromValue(String v) {
                return valueOf(v);
            }

        }


        /**
         * <p>Java class for null.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * <p>
         * <pre>
         * &lt;simpleType>
         *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
         *     &lt;enumeration value="N"/>
         *     &lt;enumeration value="Y"/>
         *   &lt;/restriction>
         * &lt;/simpleType>
         * </pre>
         * 
         */
        @XmlType(name = "")
        @XmlEnum
        public enum DirrouteOptions {

            N,
            Y;

            public String value() {
                return name();
            }

            public static CreateTran.SET.DirrouteOptions fromValue(String v) {
                return valueOf(v);
            }

        }


        /**
         * <p>Java class for null.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * <p>
         * <pre>
         * &lt;simpleType>
         *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
         *     &lt;enumeration value="N"/>
         *     &lt;enumeration value="Y"/>
         *   &lt;/restriction>
         * &lt;/simpleType>
         * </pre>
         * 
         */
        @XmlType(name = "")
        @XmlEnum
        public enum EditucOptions {

            N,
            Y;

            public String value() {
                return name();
            }

            public static CreateTran.SET.EditucOptions fromValue(String v) {
                return valueOf(v);
            }

        }


        /**
         * <p>Java class for null.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * <p>
         * <pre>
         * &lt;simpleType>
         *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
         *     &lt;enumeration value="E"/>
         *     &lt;enumeration value="N"/>
         *     &lt;enumeration value="P"/>
         *   &lt;/restriction>
         * &lt;/simpleType>
         * </pre>
         * 
         */
        @XmlType(name = "")
        @XmlEnum
        public enum FpOptions {

            E,
            N,
            P;

            public String value() {
                return name();
            }

            public static CreateTran.SET.FpOptions fromValue(String v) {
                return valueOf(v);
            }

        }


        /**
         * <p>Java class for null.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * <p>
         * <pre>
         * &lt;simpleType>
         *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
         *     &lt;enumeration value="N"/>
         *     &lt;enumeration value="Y"/>
         *   &lt;/restriction>
         * &lt;/simpleType>
         * </pre>
         * 
         */
        @XmlType(name = "")
        @XmlEnum
        public enum InqOptions {

            N,
            Y;

            public String value() {
                return name();
            }

            public static CreateTran.SET.InqOptions fromValue(String v) {
                return valueOf(v);
            }

        }


        /**
         * <p>Java class for null.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * <p>
         * <pre>
         * &lt;simpleType>
         *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
         *     &lt;enumeration value="MULTSEG"/>
         *     &lt;enumeration value="SNGLSEG"/>
         *   &lt;/restriction>
         * &lt;/simpleType>
         * </pre>
         * 
         */
        @XmlType(name = "")
        @XmlEnum
        public enum MsgtypeOptions {

            MULTSEG,
            SNGLSEG;

            public String value() {
                return name();
            }

            public static CreateTran.SET.MsgtypeOptions fromValue(String v) {
                return valueOf(v);
            }

        }


        /**
         * <p>Java class for null.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * <p>
         * <pre>
         * &lt;simpleType>
         *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
         *     &lt;enumeration value="N"/>
         *     &lt;enumeration value="Y"/>
         *   &lt;/restriction>
         * &lt;/simpleType>
         * </pre>
         * 
         */
        @XmlType(name = "")
        @XmlEnum
        public enum RecoverOptions {

            N,
            Y;

            public String value() {
                return name();
            }

            public static CreateTran.SET.RecoverOptions fromValue(String v) {
                return valueOf(v);
            }

        }


        /**
         * <p>Java class for null.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * <p>
         * <pre>
         * &lt;simpleType>
         *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
         *     &lt;enumeration value="N"/>
         *     &lt;enumeration value="Y"/>
         *   &lt;/restriction>
         * &lt;/simpleType>
         * </pre>
         * 
         */
        @XmlType(name = "")
        @XmlEnum
        public enum RemoteOptions {

            N,
            Y;

            public String value() {
                return name();
            }

            public static CreateTran.SET.RemoteOptions fromValue(String v) {
                return valueOf(v);
            }

        }


        /**
         * <p>Java class for null.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * <p>
         * <pre>
         * &lt;simpleType>
         *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
         *     &lt;enumeration value="N"/>
         *     &lt;enumeration value="Y"/>
         *   &lt;/restriction>
         * &lt;/simpleType>
         * </pre>
         * 
         */
        @XmlType(name = "")
        @XmlEnum
        public enum RespOptions {

            N,
            Y;

            public String value() {
                return name();
            }

            public static CreateTran.SET.RespOptions fromValue(String v) {
                return valueOf(v);
            }

        }


        /**
         * <p>Java class for null.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * <p>
         * <pre>
         * &lt;simpleType>
         *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
         *     &lt;enumeration value="N"/>
         *     &lt;enumeration value="Y"/>
         *   &lt;/restriction>
         * &lt;/simpleType>
         * </pre>
         * 
         */
        @XmlType(name = "")
        @XmlEnum
        public enum SerialOptions {

            N,
            Y;

            public String value() {
                return name();
            }

            public static CreateTran.SET.SerialOptions fromValue(String v) {
                return valueOf(v);
            }

        }


        /**
         * <p>Java class for null.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * <p>
         * <pre>
         * &lt;simpleType>
         *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
         *     &lt;enumeration value="R"/>
         *     &lt;enumeration value="S"/>
         *   &lt;/restriction>
         * &lt;/simpleType>
         * </pre>
         * 
         */
        @XmlType(name = "")
        @XmlEnum
        public enum SpatruncOptions {

            R,
            S;

            public String value() {
                return name();
            }

            public static CreateTran.SET.SpatruncOptions fromValue(String v) {
                return valueOf(v);
            }

        }


        /**
         * <p>Java class for null.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * <p>
         * <pre>
         * &lt;simpleType>
         *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
         *     &lt;enumeration value="N"/>
         *     &lt;enumeration value="Y"/>
         *   &lt;/restriction>
         * &lt;/simpleType>
         * </pre>
         * 
         */
        @XmlType(name = "")
        @XmlEnum
        public enum TranstatOptions {

            N,
            Y;

            public String value() {
                return name();
            }

            public static CreateTran.SET.TranstatOptions fromValue(String v) {
                return valueOf(v);
            }

        }


        /**
         * <p>Java class for null.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * <p>
         * <pre>
         * &lt;simpleType>
         *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
         *     &lt;enumeration value="N"/>
         *     &lt;enumeration value="Y"/>
         *   &lt;/restriction>
         * &lt;/simpleType>
         * </pre>
         * 
         */
        @XmlType(name = "")
        @XmlEnum
        public enum WfiOptions {

            N,
            Y;

            public String value() {
                return name();
            }

            public static CreateTran.SET.WfiOptions fromValue(String v) {
                return valueOf(v);
            }

        }

    }

}
