name: Build and Test Workflow

on:
  push:
    branches:
      - master
  pull_request:
    types: [opened, synchronize]
  workflow_dispatch:
    inputs:
      PERFORM_RELEASE:
        description: '[Release] perform release'
        required: false
        default: false
        type: boolean

jobs:
  check-permission:
    runs-on: ubuntu-latest
    steps:
      # this action will fail the whole workflow if permission check fails
      - name: check permission
        uses: zowe-actions/shared-actions/permission-check@main
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}

  build-test:
    runs-on: ubuntu-latest
    needs: check-permission
    steps: 
      - name: Checkout
        uses: actions/checkout@v2
    
      - name: Setup jFrog CLI
        uses: jfrog/setup-jfrog-cli@v2
        env:
          JF_ENV_1: ${{ secrets.JF_ARTIFACTORY_TOKEN }}

      - name: Prepare workflow
        uses: zowe-actions/shared-actions/prepare-workflow@main

      - name: Build
        working-directory: ims
        run: mvn compile

      # FIXME: until we figure
      # - name: Test
      #   working-directory: ims
      #   run: mvn test

      - name: Package
        working-directory: ims
        run: |
          mvn package -Dmaven.test.skip=true
          cd target
          mv ims-*-javadoc.jar zowe-ims-api-javadoc.jar
          mv ims-*.jar zowe-ims-api.jar

      - name: Publish
        uses: zowe-actions/shared-actions/publish@main
        if: success()
        with:
          artifacts: |
            ims/target/zowe-ims-api-javadoc.jar
            ims/target/zowe-ims-api.jar
          perform-release: ${{ github.event.inputs.PERFORM_RELEASE }}

        # define we need release stage
        # FIXME: currently we don't support bumping version on Maven build. There are
        #        two ways to fix:
        #        1. add support of Maven build in Jenkins library
        #        2. convert this project to gradle build
      # - name: Release (if necessary)
      #   if: ${{ success() && github.event.inputs.PERFORM_RELEASE == 'true' && env.IS_RELEASE_BRANCH == 'true' }}
      #   uses: zowe-actions/shared-actions/release@main